// СГЕНЕРИРОВАНО scripts/inline-i18n.ts — руками не править.
// Английские шаблоны строк L() с подстановками ({0}, {1}…).
export const INLINE_PATTERNS: readonly string[] = [
  " Attempts left today: {0}.",
  "\"Our actions are justified — it convinces the international community.\" The HQ gives THREE things at once. FIRST — a {0}-tile aura: every {1}s it drains {2}% of troops from every hostile player whose territory is in range (a percentage — \"the bigger the victim's population, the more it drains\") and converts {3}% of it to you. SECOND — betraying alliances is NOT punished with the traitor mark. THIRD — it unlocks casting \"Split\", as many times as you like while Media stands.",
  "**Your friend — {0} securities** on sign-up (instead of the usual 50). **You — a reward for each friend action:** opened the link, played, registered, won. Monthly limits below.",
  "+ Prime for {0}",
  "+ Prime for {0} month{1}",
  "+{0} gold every {1}s — {2} per minute, shown as floating text above the city. A capital doesn't scale: the income is the same no matter how many levels the city itself has.",
  "+{0} per human player",
  "+{0} per match win · up to {1}/day",
  "+{0} per minute, at least +{1} per match · up to {2}/day",
  "+{0} per nation",
  "+{0} per new achievement",
  "A SAM fires with lead from {0} tiles up, and its interceptor is faster than a nuke. Against MIRV a SAM shields its entire radius, spending its charge.",
  "A boat is free, but you can have at most {0} at once. It carries the share set by the attack slider. Against a defender with the Mining ultimate, {1}% of the landing dies on mines before the fight.",
  "A captured enemy ultimate HQ comes with the tile and works — the passive applies while the building stands. But exactly {0}s later it SELF-DESTRUCTS in a nuclear blast with fallout around it, unless you tear it down first. A yellow timer ticks above the building. Your own chosen ultimate, of course, never ticks.",
  "A depot that lives on the same railway as Dora but uses it the other way round: instead of hauling a gun to the target it sends the train itself. PASSIVE: your trade trains run twice as fast — more runs, more gold from the same stations. CAST \"Doom Train\" ({0}): mark a spot and a ticking train leaves the depot along YOUR rails. It drives to the point of your network closest to the target and detonates there with a drone-sized blast. The train is VISIBLE to everyone and carries a countdown above it — this is a threat you can answer, not a sneak attack. THE COUNTERPLAY IS DIRECT: tear up the rails in front of it. Lose the rail under its next step and it blows up THERE, short of the target — the deeper you sent it, the worse the miss. It will not run on foreign rails: another player's ground closes the segment, otherwise the train would be an unkillable surprise out of nowhere.",
  "A heavy railway gun — a building that DRIVES. It only reaches {0} tiles on its own, but it rolls along the railway network, and rails grow between your buildings. Hence the point: DORA'S RANGE IS YOUR CONSTRUCTION. To hit a neighbour, push your cities toward their border; that is not an abstract radius but territorial expansion you have to pay for and that everyone can see. The enemy looks at the map, watches your buildings creep closer, and knows what is coming — the warning is made by geography itself. CAST \"Strike\" ({1}): mark a target on any land. In range, the gun fires once its {2}s reload is done; out of range, it drives along the rails until it can reach. The shell lands INSTANTLY and cannot be intercepted: this is artillery, not a missile, and a shell should have no counterplay — all the defence lives in the haul. THE COUNTERPLAY IS NOT THE GUN BUT THE TRACKS: destroy the station behind it and it is stranded where it stands, cut off from the network. You can also kill it directly — capture it with the ground, or destroy it with drones or a nuke. Dora may be parked on allied land, but break that alliance and it detonates {3}s later. Unlocked by the \"Siege\" achievement (destroy {4} enemy buildings with drones) or for 500 blood diamonds.",
  "A multiple-warhead nuke: it splits above the target and blankets its territory with 350 separate warheads (each {0}/{1} tiles). Launch cost = {2}, rising by 15M per MIRV already launched this match: second {3}, third {4}. A ready enemy SAM shields its own radius from the warheads, spending its charge.",
  "A permanent HQ with three effects. First: the HQ ITSELF is a SAM with an intercept radius ×{0} of a regular one — a giant dome over your country. Second: while it stands, ALL your SAMs reload twice as fast. Third: the HQ unlocks the \"The Sky Is Ours\" rocket ({1} per launch): it assembles on your land for {2}s, broadcast to EVERYONE as an alarm from the first second — the carrier can be torn down (that's the counterplay). Once assembled → launch → {3}s later a wave of darkness → for {4}s fog of war falls over EVERYONE but you (in team mode your allies keep their sight). Under the fog you only see your and allied territory plus a {5}-tile ring around it and around your units.",
  "A standard ultimate HQ is {0} gold and {1}s to build. Exceptions: a second Ministry of Truth costs double, Fortifications charge {2} for each of three levels, and the \"The Sky Is Ours\" rocket (Our Sky's cast) costs {3} and assembles for {4}s.",
  "A targeted \"propaganda\" strike (not a missile). Aim at a foreign country — the game draws a \"flag\" (a 3:2 rectangle with the letter T in the center). Flag size depends on the SHARE of troops invested: from ~13 tiles tall at a small share up to ~80 at full. The target's tiles inside the flag split up: the BASE of the flag (everything but the T) goes to a new separatist bot \"Independent {nick}\" — permanently immune to collapse, in a short alliance with you for {0}s and with the victim for {1}s. And the letter T — the loyal core — STAYS WITH THE VICTIM on a {2}s timer: the victim must carve a corridor from the T to their main land in time — succeed and they keep it, fail and the surrounded T is absorbed by the separatist. Cast cost: {3} gold plus the invested troops (they burn and set the flag size; the separatist's population is multiplied by {4} so the new country is viable). If fewer than {5} target tiles fall in the flag base, the split doesn't fire and nothing is spent.",
  "A trade ban against a specific player: their ships stop bringing you gold. A temporary embargo lasts {0} minutes; the \"embargo everyone\" switch can be toggled once every {1}s.",
  "A traitor who broke an alliance defends half as well for {0}s: attacking them costs the attacker half the troops. Small consolation — their land is taken 20% slower, so there's time to fight back. The Media ultimate removes the traitor mark entirely.",
  "A transfer to an ally: by default a third of your troops, {0}s cooldown. Gold donation is enabled by a lobby setting.",
  "A warship intercepts foreign trade ships within its {0}-tile patrol radius (spotting from {1}) — the cargo goes to the interceptor in full. The Central Bank ultimate makes your ships un-interceptable.",
  "A {0}×{1} rectangle — a \"flag\". The shape isn't arbitrary: your skin fits a rectangle exactly.",
  "Architecture untethered from the ground: your buildings can WALK. The \"Relocation\" cast ({0}) takes two clicks: first a zone (its size follows the troop slider, spending up to {1}% — set more and exactly the cap is charged), then a destination on your own land. Buildings in the zone lift off their foundations and walk there at one tile per second, WORKING all the way: a silo on the march is still a silo. Ports only walk along the coast, land buildings never enter water, and every step is on YOUR territory — lose the ground under the route and the building waits, then settles where it stands. At the destination the town packs in tight. You may order the next relocation immediately, without waiting for the first to arrive.",
  "Before {0} upstream was under MIT. This is the freest entry point: do what you like, even a closed commercial game.",
  "Blocked {0}",
  "Break an alliance early and you wear the traitor mark for {0}s: your land defends half as well (though it's taken 20% slower). The Media ultimate cancels the mark entirely — with it you can betray with impunity.",
  "Builds a railway and SPAWNS trade trains to your cities, ports and airports in its rail cluster — they carry gold. Each factory rolls train spawns as many times as it has levels, while the chance itself drops with your total factory count — so a level-5 factory and five separate level-1 factories spawn the SAME number of trains. The difference is that separate factories reach DIFFERENT nodes by rail and widen the network. Rail linking range is {0} to {1} tiles. IMPORTANT: cities, ports and airports only get a station if one of YOUR factories is near; with no factory there are no trains at all.",
  "Bunker: ×{0} attacker losses and ×{1} slowdown within {2} tiles. Doesn't stack — what matters is being inside a radius, not how many bunkers.",
  "Cancel · start in {0}s",
  "Capital: “{0}”.",
  "Create a {0}",
  "Current ruleset ({0}) · runs: {1}",
  "Day {0}",
  "Diamond match wins: {0}",
  "Dispatches transit planes to your own and foreign airports. A flight earns the same as a trade ship over the same distance, but a plane flies twice as fast as a ship ({0} tiles per tick) and ignores water. Coverage radius is {1} tiles. Flights are not frequent: roughly a 1-in-{2} chance per one-second check plus a random {3}–{4}s departure delay, and about half the flights go to your own airports. Flying over another living player's territory, a plane pays them {5}% of its cargo per tick — so a long haul across half a continent delivers less than it left with. An airport joins a factory's rail cluster like a city does, and it also launches suicide drones: {6}s cooldown per airport.",
  "Each next point on a trip pays {0}% less than the one before. At most {1} points are paid per trip.",
  "Edit {0}",
  "Editing “{0}” (catalog skin). Options — 50 diamonds; your own image costs the same as a new custom skin: 200 (HD — 400).",
  "Editing “{0}”. Saving = 50 diamonds (HD — 100, upgrading to HD — 200).",
  "Error: {0}",
  "Exactly like a live player: same cap, same growth, the same {0} starting troops. Every behaviour is unlocked.",
  "Fallout pattern: “{0}”.",
  "First purchase this month — {0}× the PTS.",
  "First {0} — {1} gold or silver.",
  "Former ruleset ({0}) · runs: {1}",
  "Friend request sent: {0}",
  "Games with an ultimate picked: {0} · players: {1} · picks: {2}. Average win rate across all picked ultimates — {3}%.",
  "Games {0}",
  "Golden match reward credited: {0}",
  "Got it ({0})",
  "Grows with territory (with diminishing returns: twice the land gives noticeably less than twice the troops) plus {0} per city level. Cities are the only way to raise the cap without taking land.",
  "Hit more than {0} allied tiles and the alliance breaks automatically. Fewer and it passes as an accident.",
  "Holds a {0}-tile radius around itself. Any enemy ground attack inside that circle costs the attacker {1}× more troop losses and advances {2}× slower. The bonus does NOT stack: several bunkers on one front don't give ×10 — it's enough for the tile to fall inside at least one radius. An attacker's Tank Factory strips this bonus entirely. And the key difference from every other building: when its tile is lost, a bunker is destroyed rather than captured.",
  "Invitation to clan \"{0}\"",
  "Invited: {0}",
  "Last 30 days, matches against live players only. Average win rate across all picked ultimates — {0}%.",
  "Lasts {0} minutes, then expires on its own; you're offered an extension in advance. Allies don't carve up each other's land, and their trains pay both sides when calling at each other's stations.",
  "Levels lengthen the train: a level-3 factory has {0} cars, a level-10 one has {1}. Every car pays, so a level-3 factory earns as much as three level-1 factories. Up to {2} cars are shown on the map; the rest still pay.",
  "Log in to unlock for {0} 💎",
  "Mode: tiled ({0})",
  "Not enough LTS (need {0})",
  "On {0}:",
  "Prime is active — until {0}.",
  "Publicly points everyone at a player; the mark holds for {0}s, repeatable after {1}s. A way to steer other people's aggression without fighting yourself.",
  "Publish this screenshot to the public gallery for {0} LTS?",
  "Publish · {0} LTS",
  "Raises your population cap by {0} per LEVEL — the sum of all your cities' levels. Cities also act as stations for trade trains: a train pays gold for every stop. Level does NOT increase the per-train payout, so for population a level-N city equals N separate cities exactly, while for train income separate cities are better — more stops in the network. Price is based on the SUM of levels already built and doubles each time: {1}, capping at {2}. Your first city becomes the CAPITAL — see the separate block below.",
  "Remove {0} from friends?",
  "Revanchism slows conquest of your land across your whole territory — up to {0}× slower, the more you've been cut back from your historic peak. It does not raise the attacker's troop cost.",
  "Rows with fewer than {0} picks show no Δ. Ultimates missing from the table were not picked in this period — or are not in the game right now.",
  "Shoots down enemy missiles, drones and airborne assaults. Range grows with level: {0} tiles at level 1, about {1} at level 5, capped at {2}. Reload {3}s. A SAM fires with LEAD: it computes where the missile will enter its radius and shoots there, so the radius is strictly enforced. Its interceptor flies at speed {4} — faster than a nuke ({5}), which is why it catches up. Against MIRV it works differently: a ready SAM shields its whole radius from the warheads, spending its charge to do it. It takes longer to build than any other regular building — {6}s — so tearing one down is easier than waiting it out.",
  "Skin “{0}” created. Play under this nick to see it.",
  "Spawns trade ships to other players' ports — they carry gold, and the amount scales with DISTANCE, not level. A port's level = how many ship-spawn rolls it makes and how many times it appears in others' trade-target lists, so a level-5 port is roughly five separate ports by throughput. Separate ports, though, cover different waters and give different distances — and distance is money. A port also repairs your warships: a level-N port heals up to N ships at once, +{0} healing rate per level. With nobody to trade with (an island, all foreign ports dead) a port starts shipping to itself — you need at least two of your own ports, {1}s cooldown.",
  "Stadium: while it stands, population growth and gold income are +{0}%. CAST \"Olympic Games\" ({1}): world peace for {2}s — everyone is everyone's friend: no attacks, ships don't fire, SAMs don't intercept (missiles still fly), attacks under way are recalled. The stadium bonus rises to +{3}% for the duration. {4} min cooldown. Unlocked by the \"Olympic reserve\" achievement (earn {5} gold over your career) or for 500 blood diamonds.",
  "Stands for {0}s, then lapses. You can ask the same player again no sooner than {1}s later.",
  "Starting in {0}s",
  "Synchronizing — {0} turns left",
  "The alliance breaks automatically if your blast hits more than {0} of an ally's tiles. Fewer than that counts as an accident.",
  "The beheading ultimate. While the HQ stands: every capital you hold — your own and the captured ones — pays ×{0} ({1} a minute each); a captured capital STAYS a capital instead of becoming a plain city; a victim whose capital is under your banner cannot found a new one; attacks against each such victim are 50% more effective (per victim). HQ level = number of foreign capitals held. Nothing is permanent: lose a capital and its bonus goes, lose the HQ and everything goes out at once, trophies are demoted. A victim may raze their own capital rather than hand it over. Nations have capitals — their trophies count; tribes don't. Unlocked by the \"Standard-bearer\" achievement (capture 100 capitals over your career) or for 500 blood diamonds.",
  "The browser will not ask again. You can turn it on manually — {0}:",
  "The direct antipode of the Greens: they punish radiation, this one lives off it. PASSIVES: nuclear weapons cost {0}% less, and burnt land takes {1}x fewer troops to retake — the \"liquidators\". The second matters more than it looks: a fresh crater is normally impassable and gets walked around, but for you it is a corridor. Somebody nuked their neighbour — you are already there, and it works especially well with an airborne drop straight into the ash, where no enemy will follow. CAST \"Land Reclamation\" ({2}): instantly clears ash within radius {3}, aimed anywhere — at yourself or at another country, no asking. Every tile cleared pays {4} gold: on your own land it is minted, on someone else's it is billed out of the treasury of whoever owned that ground. The LAND OWNER pays, not the bomber: hit by a stranger's missile, and the cleanup invoice is still yours. Nobody pays for open wasteland. The payout for a whole crater is deliberately BELOW the discounted price of the missile, so bombing your own desert to farm cleanup is always a loss. \"CHERNOBYL\": any loss of the plant — destroyed by an enemy, taken with the ground, or blown up by your own hand — produces a hydrogen-scale blast and fallout on the site {5}s later. The delay is honest: whoever took the site can still walk away if they work out what they took. Unlocked by the \"Atomic\" achievement (500 nukes launched over your career) or for 500 blood diamonds.",
  "The logistics ultimate. PASSIVE: everything of yours that moves under its own power goes {0}x faster — warships, landing craft, trade ships, aircraft and trains. Drones and missiles are deliberately excluded: this is about hauling, not weapons. Your trade ships also become impossible to intercept. CAST \"Industrial Revolution\" ({1}): aim at ANY country, including your own — for {2} minutes the target moves {3}x faster and loses {4}% of its population growth. This is the first cast in the roster that cuts BOTH WAYS, and that is the whole point: to a trader it is a gift, to an ally a real favour they will ask for in chat, and to a warmonger a noose — logistics are no use to them and half their growth is gone. On yourself it is a burst window: run a landing across half the map in a minute and pay for it in troops. It cannot be refused. It does not stack: a country already in revolution cannot be hit again. Unlocked by the \"Oil Baron\" achievement (hold {5} oil rigs at once) or for 500 blood diamonds.",
  "The ministry that handles war. CAST \"Pact\" ({0}): aim at a living player's country — an alliance is forced between you for {1} minutes. Peace is symmetric: you can't hit them either. Attacks already under way roll on; only new ones are frozen. One target at a time; the same target again no sooner than {2} minutes after the pact expires. The value isn't that they stopped hitting you — it's that they now MUST fight someone else: the front with you is frozen, their army turns on a neighbour. The victim may break the pact — as ordinary treason. PASSIVE 1: whoever betrays you stays a traitor for {3}s instead of 30 (the mark is global — everyone feasts on them for a minute). PASSIVE 2: nations always accept your alliance request, up to {4} nation alliances at once. Nations don't need a pact forced on them — the passive covers them. Unlocked by the \"Betrayed\" achievement (be betrayed 20 times over your career) or for 500 blood diamonds.",
  "The only building that goes not on land but straight into the OCEAN — anywhere, even in the middle of the sea (rivers and lakes don't count, and no land within {0} tiles — it is an open-sea platform). A rig pays {1}× what a port pays per voyage, and trade ships pick it as a destination {2}× more eagerly, so traffic never stops. It also repairs your warships {3}× faster than a port. WHAT IT DOES NOT DO: a rig never sends out its own trade ships, it only receives them — hence the boosted multipliers. Trade gold grows with distance, so a rig far from your shores feeds better. WHAT IT LACKS: rails (you can't lay track at sea) and the protection of territory — there is no land around it to capture, so the rig itself cannot be captured either, and only a nuke kills it. It is not eternal though: lose your last tile and your rigs go down with you.",
  "The only place atom and hydrogen bombs launch from. A silo's price does not grow with how many you own — always {0}. After a launch it reloads for {1}s; while it's busy the next missile flies from another free one, and if none are ready the launch is simply unavailable. Salvo size counts LEVELS: a level-N silo holds N missiles at once, exactly like N separate silos. Targeting range is {2} tiles from the launch point.",
  "The only ultimate that grows on OTHER people's wealth rather than your own. Every {0}s a launch goes up: you collect {1} plus {2}% of the income every other country earned during that minute — taken straight out of their pockets. The cut is taken from INCOME over the period, not from balances: income is a bounded quantity, so the ultimate stays linear instead of snowballing late in a match. Every launch is announced to everyone with the figure attached — resentment should be aimed at you by name, or nobody would notice the tax at all. Build it on your own land or OUT AT SEA like an oil rig: the sea pad costs more but pays {3}x. Unlocked by the \"First in Space\" achievement ({4} gold over your career) or for 500 blood diamonds.",
  "The party that gave up the atom and makes everyone who didn't pay for it. THE PRICE: while the HQ stands you cannot launch any nuclear weapon at all — not your own, not from silos captured off an enemy, so conquest is no loophole. Plus -{0}% income. IN EXCHANGE: your missile silos house people like cities do (the rocket base was turned into a housing estate), troop growth +{1}%, radiation retreats from your borders into the ash field on its own, and burnt land costs {2}x fewer troops to retake. RETRIBUTION: anyone whose nuke successfully detonates takes an income penalty — one step for an atom bomb, two for a hydrogen bomb, three at once for a MIRV, zero for a water nuke (flooding is ecologically clean). A step is {3}%, the cap {4}%, lasting {5}s and refreshed by new blasts. The penalty is delivered by a CIVILIAN AIRLINER: it flies from the HQ to the crater and the punishment lands when it arrives. It cannot be shot down — it is a trade plane, not a missile. There is exactly one answer: destroy the Greens HQ while the plane is still in the air. CAST \"It's a Catastrophe!\" ({6}): hound ANY country, even one that never bombed anybody — one step into the same shared scale. The cap is shared, so spending it on a habitual bomber is pointless: it is meant for peaceful rich neighbours. The penalty deliberately leaves troop growth alone — the victim keeps a growing army with no money, which pushes them to attack. Unlocked by the \"Clean Hands\" achievement (50 wins without launching a single nuke) or for 500 blood diamonds.",
  "The price grows with each drop: {0} for the first, {1} for the second and so on. {2}% of what you send arrives behind enemy lines, and the landing spot is immune to encirclement collapse for {3}s. Air Command makes the drop free, full-strength and twice as durable.",
  "The ultimate of the small and proud. The cheapest HQ in the game ({0}). Its power depends on your place: k = 1 − your territory / the leader's. Population growth and gold income are multiplied by (1 + k): doubled for the last, ×1.5 for someone with half the leader's land, nothing for the leader. Attack and defense untouched. CAST \"Respite\" ({1} + troops): peace around you — nobody attacks you and you attack nobody (missiles and SAMs keep working), attacks under way are recalled. The attack slider sets the share of troops burned and the duration: {2}s for 20%, {3}s for 50%, {4}s for all. Pride bonuses double for the duration — a comeback window. No cooldown. Unlocked by the \"Phoenix\" achievement (hold {5}% of the map, fall to {6}%, still win) or for 500 blood diamonds.",
  "The upgrade to Rivers Back. While the HQ stands, BOTH ordinary nukes and the MIRV are unavailable — instead your silo launches THREE missiles at {0} each with a {1}–{2} tile crater: {3} than Rivers Back ({4}–{5}), and {6}. FLOOD: land becomes water forever. LANDFILL: the reverse — water becomes LAND, so you can bridge to an island, wall off a strait or cut an enemy port off from the sea; the new ground belongs to NOBODY, whoever reaches it first takes it, your enemy included. NUCLEAR STRIKE: an ordinary nuke that burns the ground and leaves fallout. All three launch from the silo on a shared cooldown, and SAMs shoot them down like any missile (an intercepted Flood or Landfill leaves a half-sized crater at the intercept point).",
  "The winning team splits +{0}, up to {1} per surviving player.",
  "There is an easier path: before {0} this upstream was MIT-licensed, with almost no conditions. Starting your own game — take that version; the MIT-era commit links are on this page.",
  "They start with {0} troops and no gold, their troop cap is a third of a human's, growth is half as fast and passive income is half.",
  "Three ways to invite: share this **link**, **create a lobby and invite** (joining via the lobby link counts too), *or* just **share your profile link** (`/@{0}`) — whoever visits is tied to you. It worked if your friend sees \"+200 securities\" under the \"Sign in\" button.",
  "Too close to {0} — place your flag at least {1} tiles from another player",
  "Too few picks to compare ({0}+ needed).",
  "Ultimates refreshed · {0} LTS left",
  "Unlock \"{0}\" for {1} blood diamonds?",
  "Unlock for {0} 💎",
  "Wait {0}s",
  "While a temple stands, your ENTIRE territory slowly creeps outward — about one ring every {0}s. Each border tile converts the nearest land tiles within {1} tiles, quietly (no \"you're under attack\"). How many depends on your temple count: {2} tiles with one temple, {3} with two, {4} with three, and so on (there is ONE border sweep per player — temples do not each run their own). ROUGH GROUND SLOWS FAITH DOWN: highland and mountains cost more than plains (the same ratios a normal attack pays), so a pass converts fewer tiles in the mountains. The radius is enough to step over narrow water — a river or strait — but not an ocean to another continent. Faith does NOT touch empty wasteland, radioactive fallout, or anyone you are currently fighting — but it does eat allied and teammate land (\"faith makes no distinction\"). THE PRICE: every temple cuts {5}% off your CURRENT passive income — 100 → 90 → 81 → 73 and onward.",
  "While the HQ stands, all your warships are pirate boats: twice as fast (two steps per tick), a flat 100K each (but one boat per 15 seconds — saving gold at the cost of time), a shell hits half as hard, and they have only 200 HP — one shell from a regular warship or two pirate ones. A swarm style: many cheap fast boats against trade and landings, but a warship sinks them one on one. PASSIVE \"silent landings\": transports launch ONLY from your ports (within {0} tiles) but send no alarm, leave no trail and stay invisible to the enemy until {1} tiles from the shore. CAST \"Blockade\" ({2} + boats): a spot in the ocean within {3} tiles of your port; your pirate boats sail there (how many — by the attack slider); on arrival they anchor and circle, and a FLAG-shaped zone rises that other nations' ships route around — a Strait of Hormuz. Size grows with the boat count: the first 10 add 10% each, then less; 15 boats — half-width {4} tiles. The only way to lift it is to kill the boats (nukes, drones): fewer alive — smaller flag. Raze or lose the HQ and everything reverts. Unlocked by the \"Black flag\" achievement (sink 500 ships AND capture 500 trade ships) or for 500 blood diamonds.",
  "While the HQ stands, any of your missile silos can launch the water missile: land inside a {0}–{1} tile crater (ragged edge) becomes water FOREVER. Cut isthmuses, sink buildings with the ground, sail a fleet where there was no route. Ordinary nukes stay available — this ult does not take them away. SAMs shoot the missile down like any other, but an intercepted one still leaves a half-sized crater where it was caught. Master it (50 launches in one match) and TERRAFORMING unlocks: three missiles instead of both nukes.",
  "While the HQ stands, every {0}s each of your finished bunkers quietly captures enemy/neutral land tiles within its defense radius — no \"you're under attack\". Capture strength depends on distance to the bunker: at the radius edge it's the base ~{1} tiles per pulse, right next to the bunker three times as much (~{2}). A bunker's base {3}-tile radius grows with HQ level: ×1.2 / ×1.5 / ×1.8 = 36 / 45 / 54 tiles. The HQ itself also \"fires\", at double the radius: 60 / 75 / 90. Bunkers cost the owner 20% less.",
  "While the HQ stands, when an enemy SEA landing hits your shore, {0}% of its troops die on the mines before the fight. Works only against sea landings — airborne assaults and ground attacks are unaffected.",
  "While the HQ stands, your airborne assault is free (normally paid), lands at full strength (normally {0}% — half is \"shot down on approach\") and holds the beachhead for {1}s (normally {2}s) — during which the landing spot is immune to being auto-collapsed by encirclement.",
  "While the HQ stands, your ground attacks ignore the enemy bunker defense bonus and lose {0}% fewer troops (≈ \"+{1}% attack power\").",
  "While the HQ stands: population grows ×{0}, gold income ×{1}, and attacks are half as effective — your attackers lose ×{2} troops (an anti-Tank Factory). The style: mass over quality — hold land by numbers and scare the neighbours. CAST \"Terror\" ({3} + troops): aim at an enemy country — for {4}s its finished buildings blow up one by one. The attack slider sets the share of troops burned and the number of blasts: {5} for 10%, {6} for 50%, {7} for all. Recast on the same target stacks. Unlocked by the \"Veteran of terror\" achievement (50 wins against real players OR 10 diamond wins) or for 500 blood diamonds.",
  "While the HQ stands: your boats can't be intercepted, and your planes pay no toll for flying over foreign territory (normally {0}% of cargo per flight tick).",
  "While the monument stands, conquering YOUR land SLOWS DOWN — the more they've cut from your historic maximum (peak), the slower: at total loss it is {0}× slower at monument level 1 and up to {1}× at level {2}. At the peak (nothing lost) — zero, so the ultimate stays quiet when an invasion begins. It does NOT raise the attacker's troop cost — it only slows them; as a side effect your own troops drain slower too (they are spent per tile given up). It MULTIPLIES with bunkers. A Tank Factory does NOT ignore it — that only strips bunker defense. LEVELS: a monument is born upgraded if you have already lost previous ones, +{3}% per level. Statue captured — the next one is level {4}; demolished — level {5}; torn down by your own hand — {6} times to reach the cap. ⚠️ A CAPTURED enemy statue is always level 1: the level lives in the monument, not in you. THE OTHER HALF OF THE ULTIMATE — REVENGE: everyone who attacked you FIRST goes on a grudge list, and your attacks against them are {7}% more effective. Anyone you struck first does not count. The list is kept AT ALL TIMES, even before the statue exists: finish it in the middle of an invasion and the revenge applies immediately to everyone who already attacked you.",
  "You added {0} as a friend",
  "You declined {0}'s request",
  "You're now friends with {0}",
  "at {0}",
  "failures: {0}",
  "from {0} gold, price counter shared with factories · {1}s build",
  "from {0} gold, price counter shared with ports · {1}s build",
  "gold multiplier ×{0}",
  "lobby modifier {0}",
  "map size {0}",
  "map {0}",
  "match timer {0} min",
  "minimum distance between structures is {0} tiles, so spreading out isn't always possible.",
  "mode {0}",
  "nations: {0}",
  "nick: {0}",
  "no silent sign-in: the account appears only via “Sign in with {0}” → the platform sign-in window",
  "not signed in → the “Sign in with {0}” button opens the platform sign-in{1}; the account is created after confirmation",
  "play under nick “{0}” to see it",
  "player already signed in to {0} → the {1} account comes up on load, no clicks; they see this screen already signed in",
  "skin “{0}”",
  "skin “{0}” for {1}",
  "solo: winner gets +{0}; leave and you get nothing",
  "spawn immunity {0}s instead of 5s",
  "starting gold {0}",
  "team match: the winning team splits +{0}, up to {1} each; die or leave and you get nothing",
  "today at {0}",
  "tomorrow at {0}",
  "{0} bots instead of 400",
  "{0} diamonds",
  "{0} each · {1}s build",
  "{0} for a live player, {1} for a tribe, and by difficulty for nations (see the AI section).",
  "{0} for the first launch, +15M for each next. Splits into 350 warheads of {1}/{2} tiles — it blankets a whole country.",
  "{0} gold for a level-1 train when the point is close, up to {1} for a long haul.",
  "{0} gold per level · {1}s build",
  "{0} gold per minute while it stands. Details in the Buildings section.",
  "{0} gold per tick — {1} per second. Tribes get half. It's background income; you won't win a war on it alone.",
  "{0} gold · {1}s build",
  "{0} gold · {1}s build · rocket {2}",
  "{0} gold · {1}s build · unlock: achievement or 500 💎",
  "{0} gold · {1}s build · {2} per launch",
  "{0} gold · {1}s build · {2} per launch · unlocked by the Hydro Engineer achievement or for 500 blood diamonds",
  "{0} gold · {1}s build · −{2}% income per temple",
  "{0} gold — almost nothing.",
  "{0} gold — beyond this the gain flattens out.",
  "{0} gold — the knee; beyond it the curve climbs steeply.",
  "{0} gold, {1}/{2}-tile radius — it burns out an entire region.",
  "{0} gold, {1}/{2}-tile radius, {3}s airport cooldown. A cheap surgical demolition — an enemy SAM or ultimate HQ, say.",
  "{0} gold, {1}/{2}-tile radius.",
  "{0} gold.",
  "{0} gold. {1} health, a shell hits for {2} — four hits sink a ship. Fires every {3}s, patrols {4} tiles, and retreats to a port for repairs below {5} health.",
  "{0} invites you to clan \"{1}\"",
  "{0} is in a lobby{1}",
  "{0} is playing{1}",
  "{0} min in",
  "{0} mo",
  "{0} name (EN)",
  "{0} players",
  "{0} tiles",
  "{0} unit type(s) disabled",
  "{0} wants to be your friend",
  "{0} wk",
  "{0}% of cargo for EVERY tick over another living player's territory — paid to the landowner. A long haul across foreign land delivers noticeably less than it left with.",
  "{0}% of the map",
  "{0}+ picks needed",
  "{0}h {1}m",
  "{0}h {1}m in",
  "{0}m",
  "{0}s from the moment the first live player joins. An empty lobby waits and doesn't start.",
  "{0}s, or {1}s when there's more than one live player. Missed it? You get {2}s more after the start and still get to play.",
  "· baked {0}×{1}",
  "· baked {0}×{1} (under 1024 — HD won't add sharpness)",
  "Δ is the gap to {0}%, the average win rate among players who picked any ultimate. That is the fair yardstick: players with no ultimate win {1}% of the time, but that is survivorship, not weakness — you only reach the slot if you were already winning.",
  "“{0}” is on — play under this nick.",
  "↻ Refresh ultimates · {0} LTS",
  "↻ Refresh · {0} LTS",
  "⭐ Golden match at {0}, winner gets {1} diamonds + 1 per rival, up to {2} → {3}",
  "⭐ Golden match won by {0}",
  "💎 Diamond match at {0}, winner gets +{1} diamonds → {2}",
  "💎 Diamond match won by {0}",
  "💎 Evening diamond match, solo, at {0}: winner gets +{1} diamonds → {2}",
  "💎 Evening diamond match, teams, at {0}: the winning team splits +{1} diamonds (up to {2} each) → {3}"
];
