// terron: РУССКИЕ ИМЕНА НАЦИЙ (стадия 2–3 локализации имён ИИ, см. LocalizeNames.ts).
//
// Имена наций генерятся из manifest.json карт и хранятся EN — это канон-ключ,
// одинаковый на всех клиентах (детерминизм симуляции не трогаем). Здесь только
// ОТОБРАЖЕНИЕ: EN → RU накладывается на клиенте, как это уже сделано для столиц
// (CAPITAL_RU) и племён (tribe.*).
//
// Покрыты нации, у которых есть запись в NATION_CAPITAL, — то есть настоящие
// страны, регионы, штаты и исторические державы (они и попадаются на картах).
// Ключа нет → показываем EN как есть (осознанный фолбэк: лучше английское имя,
// чем кривой автотранслит вроде «361 Ming III»).

export const NATION_RU: Record<string, string> = {
  // ── Страны ────────────────────────────────────────────────────────
  Afghanistan: "Афганистан",
  Albania: "Албания",
  Algeria: "Алжир",
  Andorra: "Андорра",
  Angola: "Ангола",
  "Antigua and Barbuda": "Антигуа и Барбуда",
  Argentina: "Аргентина",
  Armenia: "Армения",
  Australia: "Австралия",
  Austria: "Австрия",
  Azerbaijan: "Азербайджан",
  Bahamas: "Багамы",
  Bahrain: "Бахрейн",
  Bangladesh: "Бангладеш",
  Barbados: "Барбадос",
  Belarus: "Беларусь",
  Belgium: "Бельгия",
  Belize: "Белиз",
  Benin: "Бенин",
  Bhutan: "Бутан",
  Bolivia: "Боливия",
  "Bosnia and Herzegovina": "Босния и Герцеговина",
  Botswana: "Ботсвана",
  Brazil: "Бразилия",
  Brunei: "Бруней",
  Bulgaria: "Болгария",
  Cambodia: "Камбоджа",
  Canada: "Канада",
  "Central African Republic": "Центральноафриканская Республика",
  Chad: "Чад",
  Chile: "Чили",
  China: "Китай",
  Colombia: "Колумбия",
  Croatia: "Хорватия",
  Cuba: "Куба",
  Cyprus: "Кипр",
  "Czech Republic": "Чехия",
  Czechia: "Чехия",
  "DR Congo": "ДР Конго",
  Denmark: "Дания",
  Dominica: "Доминика",
  "Dominican Republic": "Доминиканская Республика",
  Ecuador: "Эквадор",
  Egypt: "Египет",
  England: "Англия",
  Eritrea: "Эритрея",
  Estonia: "Эстония",
  Ethiopia: "Эфиопия",
  Fiji: "Фиджи",
  Finland: "Финляндия",
  France: "Франция",
  Gabon: "Габон",
  Georgia: "Грузия",
  Germany: "Германия",
  Ghana: "Гана",
  Greece: "Греция",
  Grenada: "Гренада",
  Guatemala: "Гватемала",
  Guyana: "Гайана",
  Haiti: "Гаити",
  Honduras: "Гондурас",
  Hungary: "Венгрия",
  Iceland: "Исландия",
  India: "Индия",
  Indonesia: "Индонезия",
  Iran: "Иран",
  Iraq: "Ирак",
  Ireland: "Ирландия",
  Israel: "Израиль",
  Italia: "Италия",
  Italy: "Италия",
  Jamaica: "Ямайка",
  Japan: "Япония",
  Jordan: "Иордания",
  Kazakhstan: "Казахстан",
  Kenya: "Кения",
  Korea: "Корея",
  Kosovo: "Косово",
  Kuwait: "Кувейт",
  Laos: "Лаос",
  Latvia: "Латвия",
  Lebanon: "Ливан",
  Liberia: "Либерия",
  Libya: "Ливия",
  Liechtenstein: "Лихтенштейн",
  Lithuania: "Литва",
  Macedonia: "Македония",
  Madagascar: "Мадагаскар",
  Malaysia: "Малайзия",
  Maldives: "Мальдивы",
  Mali: "Мали",
  Malta: "Мальта",
  Mauritania: "Мавритания",
  Mexico: "Мексика",
  Micronesia: "Микронезия",
  Moldova: "Молдова",
  Monaco: "Монако",
  Mongolia: "Монголия",
  Montenegro: "Черногория",
  Morocco: "Марокко",
  Mozambique: "Мозамбик",
  Myanmar: "Мьянма",
  Namibia: "Намибия",
  Nepal: "Непал",
  Netherlands: "Нидерланды",
  "New Zealand": "Новая Зеландия",
  Nicaragua: "Никарагуа",
  Niger: "Нигер",
  Nigeria: "Нигерия",
  "North Korea": "Северная Корея",
  "North Macedonia": "Северная Македония",
  "Northern Ireland": "Северная Ирландия",
  Norway: "Норвегия",
  Oman: "Оман",
  Pakistan: "Пакистан",
  Palau: "Палау",
  Palestine: "Палестина",
  Panama: "Панама",
  "Papua New Guinea": "Папуа — Новая Гвинея",
  Paraguay: "Парагвай",
  Peru: "Перу",
  Philippines: "Филиппины",
  Poland: "Польша",
  Portugal: "Португалия",
  Qatar: "Катар",
  Romania: "Румыния",
  Russia: "Россия",
  "Russian Federation": "Российская Федерация",
  "Russian State": "Российское государство",
  "Saint Kitts and Nevis": "Сент-Китс и Невис",
  "Saint Lucia": "Сент-Люсия",
  "Saint Vincent": "Сент-Винсент",
  "St Vincent & the Grenadines": "Сент-Винсент и Гренадины",
  Samoa: "Самоа",
  "Saudi Arabia": "Саудовская Аравия",
  Scotland: "Шотландия",
  Senegal: "Сенегал",
  Serbia: "Сербия",
  Siam: "Сиам",
  "Sierra Leone": "Сьерра-Леоне",
  Singapore: "Сингапур",
  Slovakia: "Словакия",
  Slovenia: "Словения",
  "Solomon Islands": "Соломоновы Острова",
  Somalia: "Сомали",
  "South Africa": "ЮАР",
  "South Korea": "Южная Корея",
  "South Sudan": "Южный Судан",
  Spain: "Испания",
  "Sri Lanka": "Шри-Ланка",
  Sudan: "Судан",
  Suriname: "Суринам",
  Sweden: "Швеция",
  Switzerland: "Швейцария",
  "Swiss Confederation": "Швейцарская Конфедерация",
  Syria: "Сирия",
  "Syrian Arab Republic": "Сирийская Арабская Республика",
  Taiwan: "Тайвань",
  Tajikistan: "Таджикистан",
  Tanzania: "Танзания",
  Thailand: "Таиланд",
  "Timor Leste": "Восточный Тимор",
  "Timor-Leste": "Восточный Тимор",
  Tibet: "Тибет",
  "Trinidad and Tobago": "Тринидад и Тобаго",
  Tunisia: "Тунис",
  Turkey: "Турция",
  Turkiye: "Турция",
  Türkiye: "Турция",
  "Republic of Turkiye": "Турецкая Республика",
  Turkmenistan: "Туркменистан",
  Ukraine: "Украина",
  "United Arab Emirates": "ОАЭ",
  "United Kingdom": "Великобритания",
  "United States": "США",
  "United States of America": "Соединённые Штаты Америки",
  USA: "США",
  Uruguay: "Уругвай",
  Uzbekistan: "Узбекистан",
  Venezuela: "Венесуэла",
  Vietnam: "Вьетнам",
  Wales: "Уэльс",
  Yemen: "Йемен",
  Zambia: "Замбия",
  Zimbabwe: "Зимбабве",
  Transnistria: "Приднестровье",
  Abkhazia: "Абхазия",
  "South Ossetia": "Южная Осетия",
  "Republika Srpska": "Республика Сербская",
  "Republic of Armenia": "Республика Армения",
  "Republic of Azerbaijan": "Азербайджанская Республика",
  "Islamic Republic of Iran": "Исламская Республика Иран",
  "Libyan Arab Jamahiriya": "Ливийская Джамахирия",

  // ── СССР и союзные республики ─────────────────────────────────────
  USSR: "СССР",
  "Soviet Union": "Советский Союз",
  "Ukrainian SSR": "Украинская ССР",
  "Byelorussian SSR": "Белорусская ССР",
  "Kazakh SSR": "Казахская ССР",
  "Uzbek SSR": "Узбекская ССР",
  "Georgian SSR": "Грузинская ССР",
  "Azerbaijan SSR": "Азербайджанская ССР",
  "Moldavian SSR": "Молдавская ССР",
  "Kirghiz SSR": "Киргизская ССР",
  "Tajik SSR": "Таджикская ССР",
  "Turkmen SSR": "Туркменская ССР",
  "Buryat ASSR": "Бурятская АССР",
  "Komi ASSR": "Коми АССР",
  "Yakut ASSR": "Якутская АССР",
  "Tannu Tuva": "Тувинская Народная Республика",

  // ── Регионы России ────────────────────────────────────────────────
  Adygea: "Адыгея",
  "Astrakhan Oblast": "Астраханская область",
  Chechnya: "Чечня",
  Dagestan: "Дагестан",
  Ingushetia: "Ингушетия",
  "Kabardino-Balkaria": "Кабардино-Балкария",
  Kalmykia: "Калмыкия",
  "Karachay-Cherkessia": "Карачаево-Черкесия",
  "Krasnodar Krai": "Краснодарский край",
  "North Ossetia": "Северная Осетия",
  "Rostov Oblast": "Ростовская область",
  "Stavropol Krai": "Ставропольский край",
  "Irkutsk Oblast": "Иркутская область",
  Magadan: "Магадан",
  Primorsky: "Приморье",
  "Republic of Buryatia": "Республика Бурятия",

  // ── Штаты и территории США ────────────────────────────────────────
  Alabama: "Алабама",
  Alaska: "Аляска",
  Arizona: "Аризона",
  Arkansas: "Арканзас",
  California: "Калифорния",
  Colorado: "Колорадо",
  Florida: "Флорида",
  Hawaii: "Гавайи",
  Idaho: "Айдахо",
  Illinois: "Иллинойс",
  Indiana: "Индиана",
  Iowa: "Айова",
  Kansas: "Канзас",
  Kentucky: "Кентукки",
  Louisiana: "Луизиана",
  Maine: "Мэн",
  Massachusetts: "Массачусетс",
  Michigan: "Мичиган",
  Minnesota: "Миннесота",
  Mississippi: "Миссисипи",
  Missouri: "Миссури",
  Montana: "Монтана",
  Nebraska: "Небраска",
  Nevada: "Невада",
  "New Mexico": "Нью-Мексико",
  "New York": "Нью-Йорк",
  "North Carolina": "Северная Каролина",
  "North Dakota": "Северная Дакота",
  Ohio: "Огайо",
  Oklahoma: "Оклахома",
  Oregon: "Орегон",
  Pennsylvania: "Пенсильвания",
  "South Carolina": "Южная Каролина",
  "South Dakota": "Южная Дакота",
  Tennessee: "Теннесси",
  Texas: "Техас",
  Utah: "Юта",
  Vermont: "Вермонт",
  Virginia: "Виргиния",
  Washington: "Вашингтон",
  Wyoming: "Вайоминг",
  Guam: "Гуам",
  "Puerto Rico": "Пуэрто-Рико",
  "Northern Mariana Islands": "Северные Марианские Острова",

  // ── Канада ────────────────────────────────────────────────────────
  Alberta: "Альберта",
  "British Columbia": "Британская Колумбия",
  Manitoba: "Манитоба",
  "New Brunswick": "Нью-Брансуик",
  Newfoundland: "Ньюфаундленд",
  "Newfoundland and Labrador": "Ньюфаундленд и Лабрадор",
  "Nova Scotia": "Новая Шотландия",
  Nunavut: "Нунавут",
  "Northwest Territories": "Северо-Западные территории",
  Ontario: "Онтарио",
  "Prince Edward Island": "Остров Принца Эдуарда",
  "Prince-Edward": "Остров Принца Эдуарда",
  Quebec: "Квебек",
  Saskatchewan: "Саскачеван",
  Yukon: "Юкон",

  // ── Австралия ─────────────────────────────────────────────────────
  "New South Wales": "Новый Южный Уэльс",
  "Northern Territory": "Северная территория",
  Queensland: "Квинсленд",
  "South Australia": "Южная Австралия",
  Tasmania: "Тасмания",
  Victoria: "Виктория",
  "Western Australia": "Западная Австралия",

  // ── Европа: регионы и исторические земли ──────────────────────────
  Abruzzo: "Абруццо",
  Andalusia: "Андалусия",
  Apulia: "Апулия",
  Attica: "Аттика",
  Baleares: "Балеарские острова",
  Basilicata: "Базиликата",
  Bavaria: "Бавария",
  Britannia: "Британия",
  Calabria: "Калабрия",
  Campania: "Кампания",
  Catalonia: "Каталония",
  "Central Macedonia": "Центральная Македония",
  Hamburg: "Гамбург",
  Hanover: "Ганновер",
  Lombardy: "Ломбардия",
  "Mecklenburg-Schwerin": "Мекленбург-Шверин",
  Oldenburg: "Ольденбург",
  "Schleswig-Holstein": "Шлезвиг-Гольштейн",
  Sicilia: "Сицилия",
  Sicily: "Сицилия",
  Tuscany: "Тоскана",
  Tyrol: "Тироль",
  Veneto: "Венето",
  Wessex: "Уэссекс",
  Svalbard: "Шпицберген",
  "Faroe Islands": "Фарерские острова",
  Greenland: "Гренландия",

  // ── Исторические державы ──────────────────────────────────────────
  "Achaemenid Empire": "Империя Ахеменидов",
  "Africa Proconsularis": "Африка Проконсульская",
  Aegyptus: "Египет (римский)",
  "Anglo-Egyptian Sudan": "Англо-Египетский Судан",
  "Austrian Empire": "Австрийская империя",
  "Beylik of Tunis": "Тунисский бейлик",
  "Crown of Aragon": "Арагонская корона",
  "Duchy of Aquitaine": "Герцогство Аквитания",
  "Duchy of Burgundy": "Герцогство Бургундия",
  "Duchy of Normandy": "Герцогство Нормандия",
  "Emirate of Afghanistan": "Афганский эмират",
  "Emirate of Granada": "Гранадский эмират",
  "Emirate of Kuwait": "Эмират Кувейт",
  "Ethiopian Empire": "Эфиопская империя",
  "French Somaliland": "Французский Сомалиленд",
  "Hafsid Sultanate": "Государство Хафсидов",
  "Italian Eritrea": "Итальянская Эритрея",
  Judaea: "Иудея",
  "Kingdom of Egypt": "Королевство Египет",
  "Kingdom of France": "Королевство Франция",
  "Kingdom of Galicia": "Королевство Галисия",
  "Kingdom of Hejaz": "Королевство Хиджаз",
  "Kingdom of Iraq": "Королевство Ирак",
  "Kingdom of Leon": "Королевство Леон",
  "Kingdom of Majorca": "Королевство Майорка",
  "Kingdom of Navarre": "Королевство Наварра",
  "Kingdom of Portugal": "Королевство Португалия",
  "Kingdom of Sardinia": "Сардинское королевство",
  "Kingdom of Syria": "Королевство Сирия",
  "Kingdom of Valencia": "Королевство Валенсия",
  "Kingdom of Yemen": "Королевство Йемен",
  "Kingdom of the Two Sicilies": "Королевство Обеих Сицилий",
  "Marinid Sultanate": "Государство Маринидов",
  "Ottoman Empire": "Османская империя",
  "Palestine Mandate": "Британский мандат в Палестине",
  "Papal States": "Папская область",
  "Principality of Asturias": "Княжество Астурия",
  "Qajar Dynasty": "Держава Каджаров",
  "Sassanid Empire": "Держава Сасанидов",
  "Sultanate of Muscat": "Маскатский султанат",
  "Sultanate of Nejd": "Неджедский султанат",

  // ── Азия: регионы ─────────────────────────────────────────────────
  Aceh: "Ачех",
  "Andaman & Nicobar Islands": "Андаманские и Никобарские острова",
  "Andhra Pradesh": "Андхра-Прадеш",
  "Arunachal Pradesh": "Аруначал-Прадеш",
  Assam: "Ассам",
  "Azad Kashmir": "Азад Кашмир",
  Bali: "Бали",
  Balochistan: "Белуджистан",
  Bihar: "Бихар",
  Chhattisgarh: "Чхаттисгарх",
  Fujian: "Фуцзянь",
  "Gilgit-Baltistan": "Гилгит-Балтистан",
  Goa: "Гоа",
  Guangdong: "Гуандун",
  Guangxi: "Гуанси",
  Gujarat: "Гуджарат",
  Hainan: "Хайнань",
  Haryana: "Харьяна",
  Hebei: "Хэбэй",
  Heilongjiang: "Хэйлунцзян",
  "Himachal Pradesh": "Химачал-Прадеш",
  Jeju: "Чеджу",
  Jharkhand: "Джаркханд",
  Jilin: "Гирин",
  Karnataka: "Карнатака",
  Kerala: "Керала",
  "Khyber Pakhtunkhwa": "Хайбер-Пахтунхва",
  Lakshadweep: "Лакшадвип",
  Liaoning: "Ляонин",
  "Madhya Pradesh": "Мадхья-Прадеш",
  Maharashtra: "Махараштра",
  Manipur: "Манипур",
  Meghalaya: "Мегхалая",
  Mizoram: "Мизорам",
  Nagaland: "Нагаленд",
  "North Sumatra": "Северная Суматра",
  Odisha: "Одиша",
  Okinawa: "Окинава",
  Papua: "Папуа",
  Puducherry: "Пудучерри",
  Rajasthan: "Раджастхан",
  Riau: "Риау",
  Sabah: "Сабах",
  Sarawak: "Саравак",
  Shandong: "Шаньдун",
  Shanghai: "Шанхай",
  Sikkim: "Сикким",
  Sindh: "Синд",
  "South Sumatra": "Южная Суматра",
  "Tamil Nadu": "Тамилнад",
  Telangana: "Телангана",
  Tianjin: "Тяньцзинь",
  Tripura: "Трипура",
  "Uttar Pradesh": "Уттар-Прадеш",
  Uttarakhand: "Уттаракханд",
  "West Bengal": "Западная Бенгалия",
  "West Papua": "Западное Папуа",
  "West Sumatra": "Западная Суматра",
  Yunnan: "Юньнань",

  // ── Америка и Карибы: регионы ─────────────────────────────────────
  Amazonas: "Амазонас",
  Aruba: "Аруба",
  Bahia: "Баия",
  "Baja California": "Нижняя Калифорния",
  "Baja California Sur": "Южная Нижняя Калифорния",
  Bermuda: "Бермуды",
  "Cayman Islands": "Каймановы острова",
  Chihuahua: "Чиуауа",
  Curaçao: "Кюрасао",
  "Falkland Islands": "Фолклендские острова",
  "French Guiana": "Французская Гвиана",
  Guadeloupe: "Гваделупа",
  Martinique: "Мартиника",
  "New Caledonia": "Новая Каледония",
  Pará: "Пара",
  "Quintana Roo": "Кинтана-Роо",
  Sinaloa: "Синалоа",
  Sonora: "Сонора",
  Yucatan: "Юкатан",

  // ── Второй проход: имена с КРУПНЫХ карт (мир/континенты/страны), которых не
  // было в NATION_CAPITAL. Отобраны по факту присутствия на giantworldmap,
  // europe, eastasia, japan, southeastasia, middleeast, arctic и т.п. — то есть
  // ровно то, что игрок видит чаще всего.
  Antarctica: "Антарктида",
  "East Antarctica": "Восточная Антарктида",
  "West Antarctica": "Западная Антарктида",
  Siberia: "Сибирь",
  Sakhalin: "Сахалин",
  "Far Eastern Republic": "Дальневосточная республика",
  Sápmi: "Сапми",
  "East Germany": "ГДР",
  "West Germany": "ФРГ",
  "Polish People's Republic": "Польская Народная Республика",
  // Япония
  Hokkaido: "Хоккайдо",
  Tohoku: "Тохоку",
  Kanto: "Канто",
  Chubu: "Тюбу",
  Kansai: "Кансай",
  Kinki: "Кинки",
  Chugoku: "Тюгоку",
  Shikoku: "Сикоку",
  Kyushu: "Кюсю",
  Tokyo: "Токио",
  Kyoto: "Киото",
  "Mount Fuji": "Фудзи",
  Sakurajima: "Сакурадзима",
  "Sado Island": "Садо",
  "Oki Islands": "Оки",
  "Shiretoko Peninsula": "Полуостров Сиретоко",
  // Восточная и Юго-Восточная Азия
  Seoul: "Сеул",
  "Hong Kong": "Гонконг",
  Macau: "Макао",
  Java: "Ява",
  Sumatra: "Суматра",
  Sulawesi: "Сулавеси",
  Kalimantan: "Калимантан",
  Maluku: "Молуккские острова",
  "Nusa Tenggara": "Нуса-Тенггара",
  "Christmas Island": "Остров Рождества",
  "Wa State": "Ва",
  // Океания и Америка
  "Cook Islands": "Острова Кука",
  "São Paulo": "Сан-Паулу",
  // Ближний Восток (исторические протектораты и эмираты)
  "Aden Protectorate": "Протекторат Аден",
  "Baluchistan Agency": "Белуджистанское агентство",
  "British Bushehr": "Британский Бушир",
  "British Cyprus": "Британский Кипр",
  "Emirate of Asir": "Эмират Асир",
  "Imamate of Oman": "Оманский имамат",
  "Rashidi Emirate": "Эмират Рашидидов",
  "Trucial States": "Договорный Оман",

  // ── Второй заход (29.07): античность и римские провинции, города Европы,
  // Корея/Тайвань/Китай, районы Стамбула и Венеции, Скандинавия, Арктика,
  // Сибирь, космические миссии, затонувшие корабли, фонетический алфавит,
  // стороны света и ШУТОЧНЫЕ имена карт (их переводим по СМЫСЛУ, не транслитом).
  Transylvania: "Трансильвания",
  Vojvodina: "Воеводина",
  Dalmatia: "Далмация",
  Pomerania: "Померания",
  Savoy: "Савойя",
  Parma: "Парма",
  Modena: "Модена",
  Toledo: "Толедо",
  Venice: "Венеция",
  "Corsica et Sardinia": "Корсика и Сардиния",
  Achaia: "Ахайя",
  Aetolia: "Этолия",
  Alpes: "Альпы",
  Aquitania: "Аквитания",
  "Arabia Petraea": "Аравия Петрейская",
  Baetica: "Бетика",
  "Bosporan Kingdom": "Боспорское царство",
  Cappadocia: "Каппадокия",
  Cilicia: "Киликия",
  "Crown of Castile": "Корона Кастилии",
  "County of Armagnac": "Графство Арманьяк",
  "County of Provence": "Графство Прованс",
  "Cyrenaica et Creta": "Киренаика и Крит",
  Dacia: "Дакия",
  Dalriata: "Дал Риада",
  Dumnonia: "Думнония",
  "East Anglia": "Восточная Англия",
  Epirus: "Эпир",
  Ephesus: "Эфес",
  Fortriu: "Фортриу",
  Franks: "Франки",
  Galatia: "Галатия",
  "Holy Roman Empire": "Священная Римская империя",
  "Kingdom of Brittany": "Королевство Бретань",
  Laigin: "Лейнстер",
  Lusitania: "Лузитания",
  Lycia: "Ликия",
  Lydia: "Лидия",
  Lidya: "Лидия",
  "Mauretania Caesariensis": "Мавретания Цезарейская",
  "Mauretania Tingitania": "Мавретания Тингитанская",
  Mercia: "Мерсия",
  Mesopotamia: "Месопотамия",
  Miletus: "Милет",
  Moesia: "Мёзия",
  Narbonensis: "Нарбонская Галлия",
  Noricum: "Норик",
  Northumbria: "Нортумбрия",
  "Northern Uí Néill": "Северные О'Нейлы",
  "Southern Uí Néill": "Южные О'Нейлы",
  Numidia: "Нумидия",
  Pannonia: "Паннония",
  Pontus: "Понт",
  Raetia: "Реция",
  Sardes: "Сарды",
  Sparta: "Спарта",
  Strathclyde: "Стратклайд",
  Terraconensis: "Тарраконская Испания",
  Thessaly: "Фессалия",
  Thrace: "Фракия",
  Thracia: "Фракия",
  Troy: "Троя",
  Ulaid: "Улад",
  "Zayyanid Sultanate": "Государство Зайянидов",
  Circassia: "Черкесия",
  Athens: "Афины",
  Thessaloniki: "Салоники",
  Crete: "Крит",
  Rhodes: "Родос",
  Naxos: "Наксос",
  Samos: "Самос",
  Chios: "Хиос",
  Lemnos: "Лемнос",
  Lesbos: "Лесбос",
  Melos: "Милос",
  Thera: "Тира",
  Euboea: "Эвбея",
  Andros: "Андрос",
  Icaria: "Икария",
  Scyros: "Скирос",
  Cythera: "Китира",
  Ios: "Иос",
  Cos: "Кос",
  Carpathos: "Карпатос",
  Kavala: "Кавала",
  Serres: "Серре",
  Kilkis: "Килкис",
  Kassandra: "Кассандра",
  Sithonia: "Ситония",
  Polygyros: "Полийирос",
  "Mount Athos": "Афон",
  Pyrgos: "Пиргос",
  Elos: "Элос",
  Thasos: "Тасос",
  Prespa: "Преспа",
  Pelister: "Пелистер",
  Galicica: "Галичица",
  Olympia: "Олимпия",
  Marathon: "Марафон",
  Paris: "Париж",
  "City of Paris": "Париж",
  Lyon: "Лион",
  Marseille: "Марсель",
  Bordeaux: "Бордо",
  Dijon: "Дижон",
  Nice: "Ницца",
  Strasbourg: "Страсбург",
  Reims: "Реймс",
  Rouen: "Руан",
  Nantes: "Нант",
  Toulouse: "Тулуза",
  Toulon: "Тулон",
  Tours: "Тур",
  Nancy: "Нанси",
  Metz: "Мец",
  Lille: "Лилль",
  Limoges: "Лимож",
  Montpellier: "Монпелье",
  Mulhouse: "Мюлуз",
  "Orléans": "Орлеан",
  Perpignan: "Перпиньян",
  Poitiers: "Пуатье",
  Rennes: "Ренн",
  Caen: "Кан",
  Calais: "Кале",
  Cannes: "Канны",
  Amiens: "Амьен",
  Avignon: "Авиньон",
  "City of Avignon": "Авиньон",
  "Besançon": "Безансон",
  Biarritz: "Биарриц",
  Grenoble: "Гренобль",
  "La Rochelle": "Ла-Рошель",
  "Le Havre": "Гавр",
  "Le Mans": "Ле-Ман",
  "Nîmes": "Ним",
  "Saint-Étienne": "Сент-Этьен",
  "Saint-Tropez": "Сен-Тропе",
  "Pas-de-Calais": "Па-де-Кале",
  "City of Cordoba": "Кордова",
  "City of Seville": "Севилья",
  Essex: "Эссекс",
  Kent: "Кент",
  Sussex: "Суссекс",
  Suffolk: "Суффолк",
  Norfolk: "Норфолк",
  Hampshire: "Гэмпшир",
  Cumbria: "Камбрия",
  Northumberland: "Нортумберленд",
  "North Yorkshire": "Северный Йоркшир",
  Lincolnshire: "Линкольншир",
  Devon: "Девон",
  Highland: "Хайленд",
  "Argyll and Bute": "Аргайл и Бьют",
  "Dumfries and Galloway": "Дамфрис и Галловей",
  "Perthshire and Kinross": "Пертшир и Кинросс",
  Powys: "Поуис",
  Gwynedd: "Гвинед",
  Gwent: "Гвент",
  Dyfed: "Дивед",
  Dublin: "Дублин",
  Clare: "Клэр",
  Kerry: "Керри",
  Mayo: "Мейо",
  Meath: "Мит",
  Munster: "Манстер",
  Connacht: "Коннахт",
  Fermanagh: "Фермана",
  Airgialla: "Аргиалла",
  Achill: "Ахилл",
  Inisheer: "Инишир",
  Inishmann: "Инишмаан",
  Inishmore: "Инишмор",
  Busan: "Пусан",
  Daegu: "Тэгу",
  Daejeon: "Тэджон",
  Incheon: "Инчхон",
  Ulsan: "Ульсан",
  Sejong: "Седжон",
  Pyongyang: "Пхеньян",
  Kaesong: "Кэсон",
  Nampo: "Нампхо",
  Gangwon: "Канвондо",
  Kangwon: "Канвондо",
  Gyeonggi: "Кёнгидо",
  "North Chungcheong": "Северный Чхунчхон",
  "South Chungcheong": "Южный Чхунчхон",
  "North Jeolla": "Северный Чолла",
  "South Jeolla": "Южный Чолла",
  "North Gyeongsang": "Северный Кёнсан",
  "South Gyeongsang": "Южный Кёнсан",
  "North Hamgyong": "Северный Хамгён",
  "South Hamgyong": "Южный Хамгён",
  "North Hwanghae": "Северный Хванхэ",
  "South Hwanghae": "Южный Хванхэ",
  "North Pyongan": "Северный Пхёнан",
  "South Pyongan": "Южный Пхёнан",
  Ryanggang: "Янгандо",
  Chagang: "Чагандо",
  Taipei: "Тайбэй",
  "Taichung City": "Тайчжун",
  Tainan: "Тайнань",
  Kaohsiung: "Гаосюн",
  Keelung: "Цзилун",
  Hsinchu: "Синьчжу",
  Chiayi: "Цзяи",
  Hualien: "Хуалянь",
  Taitung: "Тайдун",
  Miaoli: "Мяоли",
  Taoyuan: "Таоюань",
  Penghu: "Пэнху",
  "Kinmen Island": "Цзиньмэнь",
  Lanyu: "Ланьюй",
  Beijing: "Пекин",
  Fuzhou: "Фучжоу",
  Xiamen: "Сямынь",
  Quanzhou: "Цюаньчжоу",
  Putian: "Путянь",
  Zhangzhou: "Чжанчжоу",
  Longyan: "Луньянь",
  Sanming: "Саньмин",
  Dongshan: "Дуншань",
  Dehua: "Дэхуа",
  Xianyou: "Сянью",
  Anxi: "Аньси",
  Nagasaki: "Нагасаки",
  Fukuoka: "Фукуока",
  Saga: "Сага",
  Sado: "Садо",
  Adalar: "Адалар",
  "Arnavutköy": "Арнавуткёй",
  "Avcılar": "Авджылар",
  "Bakırköy": "Бакыркёй",
  "Başakşehir": "Башакшехир",
  Beykoz: "Бейкоз",
  "Beşiktaş": "Бешикташ",
  "Büyükçekmece": "Бюйюкчекмедже",
  "Kadıköy": "Кадыкёй",
  Kocaeli: "Коджаэли",
  Maltepe: "Мальтепе",
  Pendik: "Пендик",
  Sancaktepe: "Санджактепе",
  "Sarıyer": "Сарыер",
  Sultangazi: "Султангази",
  Tuzla: "Тузла",
  "Üsküdar": "Ускюдар",
  Uskudar: "Ускюдар",
  "Çekmeköy": "Чекмекёй",
  Esenyurt: "Эсеньюрт",
  "Eyüpsultan": "Эйюпсултан",
  Fatih: "Фатих",
  Sile: "Шиле",
  "Eastern Anatolia": "Восточная Анатолия",
  "Black Sea Region": "Черноморский регион",
  Cannaregio: "Каннареджо",
  Castello: "Кастелло",
  Dorsoduro: "Дорсодуро",
  Giudecca: "Джудекка",
  Lido: "Лидо",
  Murano: "Мурано",
  "San Marco": "Сан-Марко",
  "San Polo": "Сан-Поло",
  "Santa Croce": "Санта-Кроче",
  "Sant'Elena": "Сант-Элена",
  "San Giorgio Maggiore": "Сан-Джорджо-Маджоре",
  "San Michele": "Сан-Микеле",
  Certosa: "Чертоза",
  "Le Vignole": "Ле-Виньоле",
  "Porto di Venezia": "Порт Венеции",
  Aarhus: "Орхус",
  "Skåne": "Сконе",
  "Småland": "Смоланд",
  "Närke": "Нерке",
  "Östergötland": "Эстергётланд",
  "Västergötland": "Вестергётланд",
  "Bohuslän": "Бохуслен",
  Dalsland: "Дальсланд",
  Halland: "Халланд",
  Zealand: "Зеландия",
  Funen: "Фюн",
  Bornholm: "Борнхольм",
  Ribe: "Рибе",
  Viborg: "Виборг",
  Vejle: "Вайле",
  "Lolland-Falster": "Лолланн-Фальстер",
  "North Jutland": "Северная Ютландия",
  Ringkobing: "Рингкёбинг",
  Agder: "Агдер",
  "Østlandet": "Эстланн",
  "Jan Mayen": "Ян-Майен",
  Nordaustlandet: "Северо-Восточная Земля",
  Reykjavik: "Рейкьявик",
  Westfjords: "Западные фьорды",
  Nuuk: "Нуук",
  Qaanaaq: "Каанаак",
  Qaqortoq: "Какортокк",
  Ilulissat: "Илулиссат",
  Tasiilaq: "Тасиилак",
  Ittoqqortoormiit: "Иттоккортоормиит",
  "Utqiaġvik": "Уткиагвик",
  Barents: "Баренцево море",
  Bering: "Берингово море",
  Laptev: "Море Лаптевых",
  Beaufort: "Море Бофорта",
  Weddell: "Море Уэдделла",
  Bellingshausen: "Море Беллинсгаузена",
  Amundsen: "Море Амундсена",
  Ross: "Море Росса",
  "Marie Byrd Land": "Земля Мэри Бэрд",
  Arctic: "Арктика",
  Arctica: "Арктика",
  Alert: "Алерт",
  Resolute: "Резольют",
  Igloolik: "Иглулик",
  Iqaluit: "Икалуит",
  Inuvik: "Инувик",
  Ulukhaktok: "Улукхакток",
  "Grise Fiord": "Грайс-Фьорд",
  "Pond Inlet": "Понд-Инлет",
  "Baker Lake": "Бейкер-Лейк",
  "Rankin Inlet": "Ранкин-Инлет",
  "Cambridge Bay": "Кеймбридж-Бей",
  Whitehorse: "Уайтхорс",
  Yellowknife: "Йеллоунайф",
  Anadyr: "Анадырь",
  Bilibino: "Билибино",
  Chersky: "Черский",
  Egvekinot: "Эгвекинот",
  Kamenskoye: "Каменское",
  "Petropavlovsk-Kamchatsky": "Петропавловск-Камчатский",
  Provideniya: "Провидения",
  Srednekolymsk: "Среднеколымск",
  "Ust-Kamchatsk": "Усть-Камчатск",
  Zyryanka: "Зырянка",
  Listvyanka: "Листвянка",
  "Olkhon Island": "Ольхон",
  "Bolshoy Ushkan Island": "Большой Ушканий",
  "Chivyrkuisky Bay": "Чивыркуйский залив",
  "Svyatoy Nos Peninsula": "Полуостров Святой Нос",
  "Zabaykalsky National Park": "Забайкальский нацпарк",
  "Siberian Shelf": "Сибирский шельф",
  "Apollo 11": "Аполлон-11",
  "Apollo 12": "Аполлон-12",
  "Apollo 13": "Аполлон-13",
  "Apollo 14": "Аполлон-14",
  "Apollo 15": "Аполлон-15",
  "Apollo 16": "Аполлон-16",
  "Apollo 17": "Аполлон-17",
  "Luna 1": "Луна-1",
  "Luna 9": "Луна-9",
  "Luna 16": "Луна-16",
  "Luna 17": "Луна-17",
  "Luna 21": "Луна-21",
  "Luna 24": "Луна-24",
  "Luna 25": "Луна-25",
  "Chang'e 3": "Чанъэ-3",
  "Chang'e 4": "Чанъэ-4",
  "Chang'e 5": "Чанъэ-5",
  "Chang'e 6": "Чанъэ-6",
  "Chandrayaan 1": "Чандраян-1",
  "Chandrayaan 3": "Чандраян-3",
  "Artemis II": "Артемида-2",
  "Surveyor 3": "Сервейер-3",
  Challenger: "Челленджер",
  Endurance: "Индьюранс",
  "European Space Agency": "Европейское космическое агентство",
  "African Space Agency": "Африканское космическое агентство",
  "Sagittarius A*": "Стрелец A*",
  "Perseus Arm": "Рукав Персея",
  "Centaurus Arm": "Рукав Центавра",
  "RMS Titanic": "Титаник",
  "RMS Lusitania": "Лузитания",
  "HMHS Britannic": "Британник",
  "USS Scorpion": "Скорпион",
  "USS Thresher": "Трешер",
  "K-141 Kursk": "К-141 «Курск»",
  "ARA San Juan": "Сан-Хуан",
  "INS Khukri": "Кхукри",
  "PNS Ghazi": "Гази",
  "HMAS Voyager": "Вояджер",
  "HMS K5": "K5",
  "Ever Given": "Эвер Гивен",
  "MV Dali": "Дали",
  "MV Le Joola": "Ле-Жоола",
  "MV Bukoba": "Букоба",
  "MV Butiraoi": "Бутираои",
  "MV Christena": "Кристена",
  "MV Dara": "Дара",
  "Doña Paz": "Донья Пас",
  Sewol: "Сэволь",
  "Toya Maru": "Тоя-Мару",
  "Princess Sophia": "Принцесса София",
  "Principessa Mafalda": "Принчипесса Мафальда",
  "Queen Annes Revenge": "Месть королевы Анны",
  "Flying Dutchman": "Летучий голландец",
  "Sea Diamond": "Си Даймонд",
  "Rouse Simmons": "Роуз Симмонс",
  "Titan Submersible": "Батискаф «Титан»",
  "Tampomas II": "Тампомас II",
  "Teratai Prima": "Тератай Прима",
  "TEV Wahine": "Вахине",
  "TSMS Lakonia": "Лакония",
  "SS Camorta": "Каморта",
  "SS Koombana": "Кумбана",
  "SS Valbanera": "Вальбанера",
  "SS Valencia": "Валенсия",
  "SS Waratah": "Варата",
  "SS Yarmouth Castle": "Ярмут Касл",
  "SS Yongala": "Йонгала",
  Alpha: "Альфа",
  Bravo: "Браво",
  Charlie: "Чарли",
  Delta: "Дельта",
  Echo: "Эхо",
  Foxtrot: "Фокстрот",
  Golf: "Гольф",
  Hotel: "Отель",
  Juliett: "Джульетта",
  Kilo: "Кило",
  Lima: "Лима",
  Mike: "Майк",
  November: "Ноябрь",
  Oscar: "Оскар",
  Papa: "Папа",
  Romeo: "Ромео",
  Sierra: "Сьерра",
  Tango: "Танго",
  Uniform: "Униформ",
  Victor: "Виктор",
  Whiskey: "Виски",
  "X-ray": "Рентген",
  Yankee: "Янки",
  Zulu: "Зулу",
  North: "Север",
  South: "Юг",
  East: "Восток",
  West: "Запад",
  "North East": "Северо-Восток",
  "North West": "Северо-Запад",
  "South East": "Юго-Восток",
  "South West": "Юго-Запад",
  "North North East": "Северо-Северо-Восток",
  "North North West": "Северо-Северо-Запад",
  "South South East": "Юго-Юго-Восток",
  "South South West": "Юго-Юго-Запад",
  "East North East": "Востоко-Северо-Восток",
  "East South East": "Востоко-Юго-Восток",
  "West North West": "Западо-Северо-Запад",
  "West South West": "Западо-Юго-Запад",
  Center: "Центр",
  Nord: "Север",
  Left: "Лево",
  Right: "Право",
  "West Coast": "Западное побережье",
  "Northern Region": "Северный регион",
  "Southern Region": "Южный регион",
  "Eastern Region": "Восточный регион",
  "Western Region": "Западный регион",
  "Northeastern Region": "Северо-восточный регион",
  "Northwestern Region": "Северо-западный регион",
  "Capital Region": "Столичный регион",
  "Central Island": "Центральный остров",
  "Northern Island": "Северный остров",
  "Northern Peninsula": "Северный полуостров",
  "Southern Peninsula": "Южный полуостров",
  "Inflation Island": "Остров Инфляции",
  Taxhaven: "Налоговый Рай",
  Taxes: "Налоги",
  "Non-peaceful Bot": "Немирный Бот",
  "Nuke Thrower": "Ядерный Метатель",
  Ledgerland: "Гроссбухляндия",
  "Isle of Margins": "Остров Маржи",
  "Dividend Shores": "Дивидендные Берега",
  "Fort Profit": "Форт Прибыль",
  "Market Peaks": "Рыночные Пики",
  "Cape Commerce": "Мыс Торговли",
  Anchorspire: "Якорный Шпиль",
  "Barter Bluffs": "Бартерные Утёсы",
  "Markup Mesa": "Плато Наценки",
  "Port Folio": "Порт Фолио",
  "Punch Merchant": "Купец-Кулак",
  "Train Trader": "Торговец Поездами",
  "Factory Builder": "Строитель Заводов",
  "Front Manager": "Фронт-Менеджер",
  "Box Fighter": "Коробочный Боец",
  "Cage Liberator": "Освободитель Клеток",
  "King of the Corner": "Король Угла",
  "Middle Defender": "Средний Защитник",
  "Suspicious Ally": "Подозрительный Союзник",
  "Empire of Mankind": "Империя Человечества",
  "Penguin Empire": "Империя Пингвинов",
  Penguins: "Пингвины",
  "Polar Bears": "Белые Медведи",
  Aliens: "Пришельцы",
  "Ancient Aliens": "Древние Пришельцы",
  "The Void": "Пустота",
  Atlantis: "Атлантида",
  "Santa Claus": "Дед Мороз",
  "Skid Row": "Трущобы",
  "Untitled States": "Безымянные Штаты",
  Greedland: "Жадноземье",
  "United Nations Base": "База ООН",
  "Endangered Islander": "Островитянин под Угрозой",
  "Isolated Islander": "Одинокий Островитянин",
  "Resilient Islander": "Стойкий Островитянин",
  "Rugged Islander": "Суровый Островитянин",
  "Unyielding Islander": "Несгибаемый Островитянин",
  "Vulnerable Islander": "Уязвимый Островитянин",
  "Volcano Islander": "Вулканический Островитянин",
  "North Islander": "Северный Островитянин",
  "Boaty McBoatface": "Лодка Лодочная",
  "Unsinkable II": "Непотопляемый II",
  "Duck Boat": "Утка-Лодка",
  "Ferry Neptune": "Паром «Нептун»",

  // ── Третий заход (29.07): города США и Канады, Португалия и Бразилия,
  // Египет и Персидский залив, Индонезия, Гавайи, моря и подводные хребты,
  // острова Финского залива и Фареры, индейские народы, антарктические
  // претензии и колонии, а также фикшн-имена карт (по смыслу/транслитом).
  Chicago: "Чикаго",
  Cleveland: "Кливленд",
  Detroit: "Детройт",
  Milwaukee: "Милуоки",
  Madison: "Мэдисон",
  Buffalo: "Буффало",
  Rochester: "Рочестер",
  Erie: "Эри",
  "Green Bay": "Грин-Бей",
  Duluth: "Дулут",
  Lansing: "Лансинг",
  Marquette: "Маркетт",
  Escanaba: "Эсканаба",
  Muskegon: "Маскигон",
  Saginaw: "Сагино",
  Alpena: "Алпина",
  Ashland: "Ашленд",
  Davenport: "Давенпорт",
  Wausau: "Уосо",
  Marion: "Мэрион",
  Concord: "Конкорд",
  Annapolis: "Аннаполис",
  Richmond: "Ричмонд",
  Memphis: "Мемфис",
  "West Memphis": "Западный Мемфис",
  Clarksdale: "Кларксдейл",
  "Helena-West Helena": "Хелена-Уэст-Хелена",
  "Friars Point": "Фрайарс-Пойнт",
  Tunica: "Туника",
  "Arkansas City": "Арканзас-Сити",
  Kingston: "Кингстон",
  Philly: "Филли",
  Pittsburg: "Питтсбург",
  Gary: "Гэри",
  Anchorage: "Анкоридж",
  Fairbanks: "Фэрбанкс",
  Juneau: "Джуно",
  Nome: "Ном",
  Kodiak: "Кадьяк",
  Kotzebue: "Коцебу",
  Bethel: "Бетел",
  Unalaska: "Уналашка",
  "Fort Yukon": "Форт-Юкон",
  "Prudhoe Bay": "Прадхо-Бей",
  "San Francisco": "Сан-Франциско",
  "San Jose": "Сан-Хосе",
  Oakland: "Окленд",
  Berkeley: "Беркли",
  "Palo Alto": "Пало-Алто",
  "San Mateo": "Сан-Матео",
  "San Rafael": "Сан-Рафаэль",
  Vallejo: "Вальехо",
  Novato: "Новато",
  Fremont: "Фримонт",
  Hayward: "Хейворд",
  Livermore: "Ливермор",
  Napa: "Напа",
  "Santa Rosa": "Санта-Роза",
  "Bodega Bay": "Бодега-Бей",
  Bolinas: "Болинас",
  Mendocino: "Мендосино",
  "Daly City": "Дейли-Сити",
  Hollywood: "Голливуд",
  "Beverly Hills": "Беверли-Хиллз",
  "Santa Monica": "Санта-Моника",
  Malibu: "Малибу",
  "Long Beach": "Лонг-Бич",
  "Huntington Beach": "Хантингтон-Бич",
  Pasadena: "Пасадена",
  Glendale: "Глендейл",
  Inglewood: "Инглвуд",
  Compton: "Комптон",
  Torrance: "Торранс",
  Downey: "Дауни",
  Covina: "Ковина",
  Encino: "Энсино",
  Palmdale: "Палмдейл",
  "Santa Clarita": "Санта-Кларита",
  "Santa Ana": "Санта-Ана",
  Anaheim: "Анахайм",
  "Thousand Oaks": "Таузенд-Окс",
  Fairfield: "Фэрфилд",
  "Santa Catalina": "Санта-Каталина",
  Walnut: "Уолнат",
  Sequoia: "Секвойя",
  Bardsdale: "Бардсдейл",
  "Hidden Springs": "Хидден-Спрингс",
  "L.A.X.": "Аэропорт Лос-Анджелеса",
  Rockaway: "Рокавей",
  Canarsie: "Канарси",
  Maspeth: "Маспет",
  Gravesend: "Грейвсенд",
  Breukelen: "Брёкелен",
  "Long Island Territory": "Территория Лонг-Айленд",
  "New York Colony": "Нью-Йоркская колония",
  "New Jersey Colony": "Нью-Джерсийская колония",
  "New Netherland Colony": "Новые Нидерланды",
  "Mannahatta Village": "Деревня Маннахатта",
  "Colen Donck": "Колен-Донк",
  "Horseshoe Lake": "Озеро Подкова",
  Rosedale: "Роуздейл",
  Emerald: "Эмеральд",
  Toronto: "Торонто",
  Ottawa: "Оттава",
  Halifax: "Галифакс",
  Fredericton: "Фредериктон",
  Labrador: "Лабрадор",
  Windsor: "Виндзор",
  "Thunder Bay": "Тандер-Бей",
  "North Bay": "Норт-Бей",
  "Parry Sound": "Парри-Саунд",
  "Sault Ste. Marie": "Су-Сент-Мари",
  Timmins: "Тимминс",
  Goderich: "Годерич",
  Moncton: "Монктон",
  Bonavista: "Бонависта",
  "Corner Brook": "Корнер-Брук",
  "Grand Falls": "Гранд-Фолс",
  "St Johns": "Сент-Джонс",
  "Port aux Basques": "Пор-о-Баск",
  "Gros Morne": "Грос-Морн",
  "Cape Breton Island": "Остров Кейп-Бретон",
  "Anticosti Island": "Остров Антикости",
  Acadia: "Акадия",
  Gaspesia: "Гаспези",
  Laval: "Лаваль",
  Westmount: "Уэстмаунт",
  Mirabel: "Мирабель",
  Blainville: "Бленвиль",
  Chateauguay: "Шатоге",
  "Saint-Eustache": "Сент-Эсташ",
  "Saint-Lambert": "Сен-Ламбер",
  "Pointe-aux-Trembles": "Пуант-о-Трамбль",
  "Rouyn-Noranda": "Руэн-Норанда",
  Caniapiscau: "Каниапискау",
  Manicouagan: "Маникуаган",
  "Manicouagan Island": "Остров Маникуаган",
  "Rene Levasseur Island": "Остров Рене-Левассёр",
  Mingan: "Минган",
  Melville: "Мелвилл",
  Bathurst: "Батерст",
  Yarmouth: "Ярмут",
  Wawa: "Вава",
  "Hochelaga Archipelago": "Архипелаг Ошелага",
  "Perrot Island": "Остров Перро",
  "Kanesatake Lands": "Земли Канесатаке",
  Nitassinan: "Нитассинан",
  Lamontagne: "Ламонтань",
  "Royal Mount park": "Парк Мон-Руаяль",
  "Tour Boissinot": "Башня Буассино",
  "Relais Gabriel": "Реле Габриэль",
  Lisbon: "Лиссабон",
  Cascais: "Кашкайш",
  Setubal: "Сетубал",
  Amadora: "Амадора",
  Almada: "Алмада",
  Barreiro: "Баррейру",
  Montijo: "Монтижу",
  Sesimbra: "Сезимбра",
  Ericeira: "Эрисейра",
  "Alverca do Ribatejo": "Алверка-ду-Рибатежу",
  "Samora Correia": "Самора-Коррейя",
  "Pero Pinheiro": "Перу-Пиньейру",
  Pegoes: "Пегойнш",
  Carvalhal: "Карвалял",
  "Vargem Grande": "Варжень-Гранди",
  "São João": "Сан-Жуан",
  Botafogo: "Ботафого",
  Recreio: "Рекрейю",
  Floresta: "Флореста",
  "Paraíso": "Параизу",
  "Bom Futuro": "Бон-Футуру",
  "Boa Esperança": "Боа-Эсперанса",
  "Esperito Santo": "Эспириту-Санту",
  "Castro Alves": "Кастру-Алвис",
  Correnteza: "Коррентеза",
  "Amaturá": "Аматура",
  "São Paulo de Olivença": "Сан-Паулу-ди-Оливенса",
  "Caturiá": "Катуриа",
  Baia: "Байя",
  "União": "Униан",
  "Monte Cristo": "Монте-Кристо",
  Cairo: "Каир",
  Alexandria: "Александрия",
  Heliopolis: "Гелиополь",
  Damietta: "Дамьетта",
  "El Mansoura": "Эль-Мансура",
  "El Senbellawein": "Эс-Сенбеллавейн",
  "Mit Ghamr": "Мит-Гамр",
  Faraskur: "Фарескур",
  "New Delhi": "Нью-Дели",
  Punjab: "Пенджаб",
  "Jammu and Kashmir": "Джамму и Кашмир",
  "Abu Dhabi": "Абу-Даби",
  Sharjah: "Шарджа",
  "Ras Al Khaymah": "Рас-эль-Хайма",
  Fujayrah: "Эль-Фуджайра",
  "Al Wakrah": "Эль-Вакра",
  "Ar Rayyān": "Эр-Райян",
  Muscat: "Маскат",
  Musandam: "Мусандам",
  "Al Batnah North": "Эль-Батина Северная",
  "Al Batnah South": "Эль-Батина Южная",
  "Al Buraymi": "Эль-Бурайми",
  "Al Dhahira": "Эз-Захира",
  "Ad Dakhliyah": "Эд-Дахилия",
  "Ash Sharqiyah": "Эш-Шаркия",
  Bushehr: "Бушир",
  Fars: "Фарс",
  Hormozgan: "Хормозган",
  Kerman: "Керман",
  "Sistan and Baluchestan": "Систан и Белуджистан",
  Rif: "Риф",
  Pamir: "Памир",
  Manchurian: "Маньчжурия",
  "Bangka Belitung": "Банка-Белитунг",
  Bengkulu: "Бенгкулу",
  Jambi: "Джамби",
  Lampung: "Лампунг",
  "Riau Islands": "Острова Риау",
  "Cahaya Bahari": "Чахая-Бахари",
  "Turks and Caicos": "Тёркс и Кайкос",
  "British Virgin Islands": "Британские Виргинские острова",
  "U.S. Virgin Islands": "Американские Виргинские острова",
  "Sint Maarten": "Синт-Мартен",
  Montserrat: "Монтсеррат",
  "San Andres": "Сан-Андрес",
  "Guantanamo Bay": "Гуантанамо",
  Clipperton: "Клиппертон",
  Stanley: "Порт-Стэнли",
  "East Falkland": "Восточный Фолкленд",
  "Fox Bay": "Фокс-Бей",
  Oahu: "Оаху",
  Maui: "Мауи",
  Kauai: "Кауаи",
  Lanai: "Ланаи",
  Molokai: "Молокаи",
  Niihau: "Ниихау",
  Kahoolawe: "Кахоолаве",
  Hilo: "Хило",
  Kona: "Кона",
  Gambier: "Гамбье",
  Naturaliste: "Натуралист",
  "Wickham and Fitzroy": "Уикем и Фицрой",
  Baltic: "Балтийское море",
  Atlantic: "Атлантика",
  Pacific: "Тихий океан",
  Indian: "Индийский океан",
  Asia: "Азия",
  Banda: "Море Банда",
  Kara: "Карское море",
  "Weddell Plain": "Равнина Уэдделла",
  "Nazca Ridge": "Хребет Наска",
  "Walvis Ridge": "Китовый хребет",
  "Shatsky Falls": "Возвышенность Шатского",
  Udintsev: "Разлом Удинцева",
  "Kermadec Mountains": "Хребет Кермадек",
  "Mariana Mountains": "Марианский хребет",
  "Hawaiian-Emperor Lakes": "Гавайско-Императорский хребет",
  "Lake Kerguerlen": "Плато Кергелен",
  "Lake Kerguelen": "Плато Кергелен",
  "East Pacific Plains": "Восточно-Тихоокеанская равнина",
  "Falkland-Agulhas": "Фолкленд-Агульяс",
  "Manihiki Valley": "Долина Манихики",
  "Lelukuau Mountains": "Горы Лелукуау",
  "Mount Babel": "Гора Бабель",
  "Mount Roland": "Гора Роланд",
  "Ushtishkukamiu River": "Река Уштишкукамиу",
  "Cape Khoboy": "Мыс Хобой",
  "Ogoi Island": "Остров Огой",
  Baikalovsk: "Байкальск",
  Polykarpovsk: "Поликарповск",
  Shiberia: "Шибирь",
  Zheleznogzorzkz: "Железногорск",
  "Aspö": "Аспё",
  "Borstö": "Бёрстё",
  "Brunskär": "Брунскер",
  "Hellsö": "Хелльсё",
  "Högsåra": "Хёгсора",
  Jurmo: "Юрмо",
  Kopparholm: "Коппархольм",
  "Korpoström": "Корпострём",
  "Kyrkogardsö": "Чюркогордсё",
  "Kälö": "Челё",
  "Kökar": "Чёкар",
  "Långholm": "Лонгхольм",
  "Nötö": "Нётё",
  "Stenskär": "Стенскер",
  "Trunsö": "Трунсё",
  "Utö": "Утё",
  "Vanö": "Ванё",
  "Örö": "Эрё",
  Hammarsboda: "Хаммарсбода",
  Aros: "Арос",
  Hjort: "Хьорт",
  "Eysturoy Region": "Эстурой",
  "Streymoy Region": "Стреймой",
  "Suduroy Region": "Сувурой",
  "Sandoy Region": "Сандой",
  "Vagar Region": "Воар",
  "Nordoyar Region": "Нордойар",
  Vlissingen: "Флиссинген",
  Zeewolf: "Зевольф",
  Zeehaen: "Зехан",
  Atsiki: "Атсики",
  Evgatis: "Эвгатис",
  Kotsinas: "Коцинас",
  Portianou: "Портиану",
  Aberdeenshire: "Абердиншир",
  Brest: "Брест",
  Chopin: "Шопен",
  Podgorie: "Подгорье",
  "Castillo de Olite": "Кастильо-де-Олите",
  Angamos: "Ангамос",
  "Christiana Hama": "Кристиана Хама",
  "Argentina Claim": "Претензия Аргентины",
  "Argentinian Claim": "Претензия Аргентины",
  "Chile Claim": "Претензия Чили",
  "Chilean Claim": "Претензия Чили",
  "French Claim": "Претензия Франции",
  "Norway Claim": "Претензия Норвегии",
  "Norwegian Claim": "Претензия Норвегии",
  "Australian Claim": "Претензия Австралии",
  "Lower Australian Claim": "Нижняя претензия Австралии",
  "Upper Australian Claim": "Верхняя претензия Австралии",
  "New Zealand Claim": "Претензия Новой Зеландии",
  "United Kingdom Claim": "Претензия Великобритании",
  "Australian Colony": "Австралийская колония",
  "Chilean Colony": "Чилийская колония",
  "Chinese Colony": "Китайская колония",
  "Indian Colony": "Индийская колония",
  "Irish Colony": "Ирландская колония",
  "Japanese Colony": "Японская колония",
  "North Korean Colony": "Северокорейская колония",
  "Polish Colony": "Польская колония",
  "Russian Colony": "Русская колония",
  "South African Colony": "Южноафриканская колония",
  "United Kingdom Colony": "Британская колония",
  "United States Colony": "Американская колония",
  "Southern African State": "Южноафриканское государство",
  "Southern South West Africa": "Южная Юго-Западная Африка",
  "Center Africa": "Центральная Африка",
  "Shinnecock Nation": "Народ Шиннекок",
  "Montaukett Nation": "Народ Монтаукетт",
  "Unkechaug Nation": "Народ Ункечауг",
  "Munsee Tribe": "Племя Манси",
  "Unami Tribe": "Племя Унами",
  Unalachtigo: "Уналахтиго",
  Siwanoy: "Сиваной",
  Weckquaesgeek: "Веквескик",
  Chinook: "Чинук",
  Kaupashkueiat: "Каупашкуэят",
  "Nort Pole": "Севрный полюс",
  Amtarctica: "Амтарктида",
  Bangledash: "Бангладыш",
  Brailzil: "Бразилея",
  Cananada: "Канканада",
  Calizonia: "Калифорзона",
  Endonisia: "Индонезея",
  "Graet Brian": "Велкобритания",
  Madalplascar: "Мадаплгаскар",
  Napolidier: "Наполидье",
  "New Sealand": "Новая Зеляндия",
  Nicargo: "Никарго",
  Rusha: "Рассея",
  Ucryin: "Укрыина",
  "Free Pluto State": "Свободное Государство Плутон",
  Foundland: "Найдландия",
  Ikeland: "Айкландия",
  Binland: "Бинляндия",
  Agraphistan: "Аграфистан",
  Plackitstan: "Плакитстан",
  Libraria: "Библиотекария",
  Lunareth: "Лунарет",
  Myrkwind: "Мрачноветер",
  Sylvoria: "Сильвория",
  Rollandia: "Ролландия",
  Alberia: "Альберия",
  Concordia: "Конкордия",
  Valamara: "Валамара",
  Eris: "Эрида",
  Iram: "Ирам",
  "Anazom Warehouse": "Склад Аназон",
  "Biosphere Conmune": "Биосферная Коммуна",
  "DarkEarth Station": "Станция Тёмная Земля",
  "MyBios Station": "Станция МайБиос",
  "Xederma Enclave": "Анклав Кседерма",
  "Aywen Enclave": "Анклав Эйвен",
  "Outer Enclave": "Внешний Анклав",
  "Inner Tribe": "Внутреннее Племя",
  Blockhead: "Болванчик",
  Blocko: "Блочный",
  Blockedhof: "Блокенгоф",
  Boxedin: "Взаперти",
  Boxey: "Коробочный",
  Boximilian: "Боксимилиан",
  Bowtie: "Бабочка",
  Crossed: "Скрещённый",
  Zigzag: "Зигзаг",
  Diagonalf: "Диагональф",
  Rectanglo: "Прямоугольникус",
  Squarm: "Квадрачервь",
  Scaler: "Масштабатор",
  Slasher: "Резак",
  Repeater: "Повторятель",
  Splain: "Сплейн",
  Harlequin: "Арлекин",
  Hacker: "Хакер",
  Fullsender: "Вабанк",
  "Evan The Dev": "Эван-Разработчик",
  "Didier's Left Hand": "Левая рука Дидье",
  "Didier's Right Foot": "Правая нога Дидье",
  "Limace qui passe Tribe": "Племя Проползающего Слизня",
  "Furti Two Tribe": "Племя Фурти-Два",
  "Bearguin Aliance": "Медвепингвиний Альянс",
  "Dophlin Confeteracy": "Дельфинья Конфедерация",
  "Leafer Confederation": "Лиственная Конфедерация",
  "Mell Confederation": "Конфедерация Мелл",
  "PinPin Confederation": "Конфедерация ПинПин",
  "Scorpionem Confederation": "Скорпионья Конфедерация",
  "Kumiz Confederation": "Конфедерация Кумыз",
  "United Bara Estimates": "Объединённые Бара Оценки",
  Elfsbeer: "Эльфийское Пиво",
  Beeline: "Пчелиная Тропа",
  Flukes: "Хвостовые Плавники",
  Flora: "Флора",
  Grace: "Грация",
  Elaine: "Элейн",
  Jermaine: "Джермейн",
  Nigel: "Найджел",
  Shaka: "Шака",
  Buckly: "Бакли",
  Huggins: "Хаггинс",
  Clarion: "Кларион",
  Albermarle: "Албемарл",
  "Saunders and Dunbar": "Сондерс и Данбар",
  Harborwick: "Харборвик",
  Weston: "Уэстон",
  Korinthal: "Коринталь",
  Arryn: "Аррен",
  Modwyn: "Модвин",
  Veden: "Веден",
  Eastos: "Истос",
  "East Cornea": "Восточная Роговица",
  "West Cornea": "Западная Роговица",
  "North Lefonia": "Северная Лефония",
  "South Lefonia": "Южная Лефония",
  "North Vitamen": "Северный Витамин",
  "South Vitamen": "Южный Витамин",
  Pants: "Штаны",
  Sore: "Болячка",
  "Papa No Guine": "Папа Не Гвинея",
  Irap: "Ирап",
  Idoly: "Идоли",
  Slomia: "Сломия",
  Mongoalina: "Монголина",
  Xico: "Ксико",
  Vola: "Вола",
  Laya: "Лайя",
  Kene: "Кене",
  Keeko: "Кико",
  Kanka: "Канка",
  Jina: "Джина",
  Jonqal: "Джонкаль",
  Eban: "Эбан",
  Echur: "Эчур",
  Eleske: "Элеске",
  Ellach: "Эллах",
  Deno: "Дено",
  Dexted: "Декстед",
  Derorrim: "Дероррим",
  Gridsly: "Гридсли",
  Chapan: "Чапан",
  Chanchur: "Чанчур",
  Checkheir: "Чекхейр",
  Cornerlius: "Корнерлиус",
  Calphe: "Кальфе",
  Cajual: "Кажуал",
  Bolonta: "Болонта",
  Boufou: "Буфу",
  Bafiling: "Бафилинг",
  Azakah: "Азаках",
  Aregano: "Арегано",
  "Andrew-Basin": "Бассейн Эндрю",
  Mazely: "Мазели",
  Morvay: "Морвэй",
  Mungui: "Мунгуи",
  Marara: "Марара",
  Mangueya: "Мангейя",
  Maferenya: "Маференья",
  Ratoma: "Ратома",
  Coyah: "Койя",
  Dubreka: "Дубрека",
  Forecariah: "Форекария",
  Dioumaya: "Диумайя",
  Kaback: "Кабак",
  "Koba-Tatema": "Коба-Татема",
  Kenende: "Кененде",
  Fotoba: "Фотоба",
  Tamouta: "Тамута",
  Yelibane: "Йелибане",
  Dandaya: "Дандайя",
  Gomati: "Гомати",
  Gallieni: "Галлиени",
  "Ilot Cabri": "Иле-Кабри",
  Prina: "Прина",
  Fata: "Фата",
  Uddas: "Уддас",
  Tuage: "Туаге",
  Yukant: "Юкант",
  Zematas: "Зематас",
  Sheremsah: "Шеремсах",
  Shilha: "Шильха",
  "Nawan-mirri": "Наван-мирри",
  Dubay: "Дубай",
  Aga: "Ага",
  Brixs: "Бриксы",
  "San Carlos": "Сан-Карлос",
  "San Fernando": "Сан-Фернандо",
  "Blazzy Tribe": "Племя Блэззи",
  "Plaido": "Плайдо",
};
