// terron: СТОЛИЦЫ — имена столиц. Считается в СИМУЛЯЦИИ при назначении столицы
// (детерминизм): нация с именем реальной страны → её реальная столица; игрок или
// нация-регион (провинция/фикшн) → детерминированный рандом из пула. Хранится EN
// (канон-ключ), RU-форма накладывается на клиенте по CAPITAL_RU. Спека: CAPITALS.md

import { PseudoRandom } from "../PseudoRandom";
import { simpleHash } from "../Util";

// Имя нации (канон EN, как в manifest.json) → реальная столица (EN).
export const NATION_CAPITAL: Record<string, string> = {
  // ── Суверенные страны ──────────────────────────────────────────────
  Russia: "Moscow",
  "Russian Federation": "Moscow",
  "Russian State": "Moscow",
  USSR: "Moscow",
  "Soviet Union": "Moscow",
  "United States": "Washington",
  "United States of America": "Washington",
  USA: "Washington",
  China: "Beijing",
  Germany: "Berlin",
  France: "Paris",
  "United Kingdom": "London",
  Italy: "Rome",
  Italia: "Rome",
  Spain: "Madrid",
  Portugal: "Lisbon",
  Poland: "Warsaw",
  Ukraine: "Kyiv",
  Belarus: "Minsk",
  Turkey: "Ankara",
  Turkiye: "Ankara",
  Türkiye: "Ankara",
  "Republic of Turkiye": "Ankara",
  Japan: "Tokyo",
  India: "New Delhi",
  Brazil: "Brasília",
  Canada: "Ottawa",
  Mexico: "Mexico City",
  Argentina: "Buenos Aires",
  Australia: "Canberra",
  Egypt: "Cairo",
  Iran: "Tehran",
  "Islamic Republic of Iran": "Tehran",
  Iraq: "Baghdad",
  "Saudi Arabia": "Riyadh",
  Kazakhstan: "Astana",
  Mongolia: "Ulaanbaatar",
  Sweden: "Stockholm",
  Norway: "Oslo",
  Finland: "Helsinki",
  Denmark: "Copenhagen",
  Netherlands: "Amsterdam",
  Belgium: "Brussels",
  Switzerland: "Bern",
  "Swiss Confederation": "Bern",
  Austria: "Vienna",
  Greece: "Athens",
  Romania: "Bucharest",
  Bulgaria: "Sofia",
  Hungary: "Budapest",
  Czechia: "Prague",
  "Czech Republic": "Prague",
  Slovakia: "Bratislava",
  Serbia: "Belgrade",
  Croatia: "Zagreb",
  Ireland: "Dublin",
  Iceland: "Reykjavik",
  Afghanistan: "Kabul",
  Pakistan: "Islamabad",
  Bangladesh: "Dhaka",
  Indonesia: "Jakarta",
  Thailand: "Bangkok",
  Siam: "Bangkok",
  Vietnam: "Hanoi",
  "South Korea": "Seoul",
  "North Korea": "Pyongyang",
  Korea: "Seoul",
  Philippines: "Manila",
  Malaysia: "Kuala Lumpur",
  Myanmar: "Naypyidaw",
  Nigeria: "Abuja",
  Ethiopia: "Addis Ababa",
  Kenya: "Nairobi",
  "South Africa": "Pretoria",
  Algeria: "Algiers",
  Morocco: "Rabat",
  Angola: "Luanda",
  Libya: "Tripoli",
  "Libyan Arab Jamahiriya": "Tripoli",
  Sudan: "Khartoum",
  "South Sudan": "Juba",
  Colombia: "Bogotá",
  Venezuela: "Caracas",
  Peru: "Lima",
  Chile: "Santiago",
  Bolivia: "Sucre",
  Ecuador: "Quito",
  Paraguay: "Asunción",
  Uruguay: "Montevideo",
  Guyana: "Georgetown",
  Suriname: "Paramaribo",
  Armenia: "Yerevan",
  "Republic of Armenia": "Yerevan",
  Georgia: "Tbilisi",
  Azerbaijan: "Baku",
  "Republic of Azerbaijan": "Baku",
  Uzbekistan: "Tashkent",
  Turkmenistan: "Ashgabat",
  Tajikistan: "Dushanbe",
  Israel: "Jerusalem",
  Syria: "Damascus",
  "Syrian Arab Republic": "Damascus",
  Jordan: "Amman",
  Lebanon: "Beirut",
  "New Zealand": "Wellington",
  Cuba: "Havana",
  Albania: "Tirana",
  Estonia: "Tallinn",
  Latvia: "Riga",
  Lithuania: "Vilnius",
  Slovenia: "Ljubljana",
  Qatar: "Doha",
  "United Arab Emirates": "Abu Dhabi",
  Oman: "Muscat",
  Yemen: "Sanaa",
  Bahrain: "Manama",
  Kuwait: "Kuwait City",
  Andorra: "Andorra la Vella",
  Monaco: "Monaco",
  Liechtenstein: "Vaduz",
  Malta: "Valletta",
  Cyprus: "Nicosia",
  Kosovo: "Pristina",
  Montenegro: "Podgorica",
  "North Macedonia": "Skopje",
  Macedonia: "Skopje",
  "Bosnia and Herzegovina": "Sarajevo",
  Moldova: "Chișinău",
  Nepal: "Kathmandu",
  Bhutan: "Thimphu",
  "Sri Lanka": "Colombo",
  Maldives: "Malé",
  Cambodia: "Phnom Penh",
  Laos: "Vientiane",
  Brunei: "Bandar Seri Begawan",
  Singapore: "Singapore",
  "Timor Leste": "Dili",
  "Timor-Leste": "Dili",
  Taiwan: "Taipei",
  Fiji: "Suva",
  Samoa: "Apia",
  "Papua New Guinea": "Port Moresby",
  "Solomon Islands": "Honiara",
  Palau: "Ngerulmud",
  Micronesia: "Palikir",
  Ghana: "Accra",
  Senegal: "Dakar",
  Mali: "Bamako",
  Niger: "Niamey",
  Chad: "N'Djamena",
  Mauritania: "Nouakchott",
  Gabon: "Libreville",
  "Central African Republic": "Bangui",
  "DR Congo": "Kinshasa",
  Benin: "Porto-Novo",
  Liberia: "Monrovia",
  "Sierra Leone": "Freetown",
  Eritrea: "Asmara",
  Somalia: "Mogadishu",
  Tanzania: "Dodoma",
  Mozambique: "Maputo",
  Zambia: "Lusaka",
  Zimbabwe: "Harare",
  Botswana: "Gaborone",
  Namibia: "Windhoek",
  Madagascar: "Antananarivo",
  Guatemala: "Guatemala City",
  Honduras: "Tegucigalpa",
  Nicaragua: "Managua",
  Panama: "Panama City",
  Belize: "Belmopan",
  Haiti: "Port-au-Prince",
  "Dominican Republic": "Santo Domingo",
  Jamaica: "Kingston",
  Bahamas: "Nassau",
  Barbados: "Bridgetown",
  Dominica: "Roseau",
  Grenada: "St. George's",
  "Trinidad and Tobago": "Port of Spain",
  "Antigua and Barbuda": "Saint John's",
  "Saint Kitts and Nevis": "Basseterre",
  "Saint Lucia": "Castries",
  "Saint Vincent": "Kingstown",
  "St Vincent & the Grenadines": "Kingstown",
  Palestine: "Ramallah",
  "Palestine Mandate": "Jerusalem",

  // ── Исторические державы ───────────────────────────────────────────
  "Achaemenid Empire": "Persepolis",
  "Sassanid Empire": "Ctesiphon",
  "Qajar Dynasty": "Tehran",
  "Ottoman Empire": "Constantinople",
  "Austrian Empire": "Vienna",
  "Papal States": "Rome",
  Aegyptus: "Alexandria",
  "Africa Proconsularis": "Carthage",
  Judaea: "Jerusalem",
  Attica: "Athens",
  "Ethiopian Empire": "Addis Ababa",
  "Anglo-Egyptian Sudan": "Khartoum",
  "Italian Eritrea": "Asmara",
  "French Somaliland": "Djibouti",
  "Kingdom of France": "Paris",
  "Kingdom of Portugal": "Lisbon",
  "Kingdom of Egypt": "Cairo",
  "Kingdom of Iraq": "Baghdad",
  "Kingdom of Syria": "Damascus",
  "Kingdom of Hejaz": "Mecca",
  "Kingdom of Yemen": "Sanaa",
  "Kingdom of the Two Sicilies": "Naples",
  "Kingdom of Sardinia": "Turin",
  "Kingdom of Navarre": "Pamplona",
  "Kingdom of Leon": "León",
  "Kingdom of Majorca": "Palma",
  "Kingdom of Valencia": "Valencia",
  "Kingdom of Galicia": "Santiago de Compostela",
  "Principality of Asturias": "Oviedo",
  "Crown of Aragon": "Zaragoza",
  "Emirate of Granada": "Granada",
  "Emirate of Kuwait": "Kuwait City",
  "Emirate of Afghanistan": "Kabul",
  "Sultanate of Nejd": "Riyadh",
  "Sultanate of Muscat": "Muscat",
  "Beylik of Tunis": "Tunis",
  "Hafsid Sultanate": "Tunis",
  "Marinid Sultanate": "Fez",
  "Duchy of Normandy": "Rouen",
  "Duchy of Aquitaine": "Bordeaux",
  "Duchy of Burgundy": "Dijon",
  "Tannu Tuva": "Kyzyl",
  Tibet: "Lhasa",
  Britannia: "London",
  Wessex: "Winchester",
  Tunisia: "Tunis",

  // ── Британские нации ───────────────────────────────────────────────
  England: "London",
  Scotland: "Edinburgh",
  Wales: "Cardiff",
  "Northern Ireland": "Belfast",

  // ── Постсоветские республики / непризнанные ────────────────────────
  "Ukrainian SSR": "Kyiv",
  "Byelorussian SSR": "Minsk",
  "Kazakh SSR": "Alma-Ata",
  "Kirghiz SSR": "Frunze",
  "Tajik SSR": "Dushanbe",
  "Turkmen SSR": "Ashgabat",
  "Uzbek SSR": "Tashkent",
  "Georgian SSR": "Tbilisi",
  "Azerbaijan SSR": "Baku",
  "Moldavian SSR": "Chișinău",
  Transnistria: "Tiraspol",
  Abkhazia: "Sukhumi",
  "South Ossetia": "Tskhinvali",
  "Republika Srpska": "Banja Luka",

  // ── Субъекты России ────────────────────────────────────────────────
  "Republic of Buryatia": "Ulan-Ude",
  "Buryat ASSR": "Ulan-Ude",
  Chechnya: "Grozny",
  Dagestan: "Makhachkala",
  Ingushetia: "Magas",
  Adygea: "Maykop",
  Kalmykia: "Elista",
  "Kabardino-Balkaria": "Nalchik",
  "Karachay-Cherkessia": "Cherkessk",
  "North Ossetia": "Vladikavkaz",
  "Komi ASSR": "Syktyvkar",
  "Yakut ASSR": "Yakutsk",
  "Astrakhan Oblast": "Astrakhan",
  "Irkutsk Oblast": "Irkutsk",
  "Rostov Oblast": "Rostov-on-Don",
  "Krasnodar Krai": "Krasnodar",
  "Stavropol Krai": "Stavropol",
  Primorsky: "Vladivostok",
  Magadan: "Magadan",

  // ── Штаты США ──────────────────────────────────────────────────────
  Alabama: "Montgomery",
  Alaska: "Juneau",
  Arizona: "Phoenix",
  Arkansas: "Little Rock",
  California: "Sacramento",
  Colorado: "Denver",
  Florida: "Tallahassee",
  Hawaii: "Honolulu",
  Idaho: "Boise",
  Illinois: "Springfield",
  Indiana: "Indianapolis",
  Iowa: "Des Moines",
  Kansas: "Topeka",
  Kentucky: "Frankfort",
  Louisiana: "Baton Rouge",
  Maine: "Augusta",
  Massachusetts: "Boston",
  Michigan: "Lansing",
  Minnesota: "Saint Paul",
  Mississippi: "Jackson",
  Missouri: "Jefferson City",
  Montana: "Helena",
  Nebraska: "Lincoln",
  Nevada: "Carson City",
  "New Mexico": "Santa Fe",
  "New York": "Albany",
  "North Carolina": "Raleigh",
  "North Dakota": "Bismarck",
  Ohio: "Columbus",
  Oklahoma: "Oklahoma City",
  Oregon: "Salem",
  Pennsylvania: "Harrisburg",
  "South Carolina": "Columbia",
  "South Dakota": "Pierre",
  Tennessee: "Nashville",
  Texas: "Austin",
  Utah: "Salt Lake City",
  Vermont: "Montpelier",
  Virginia: "Richmond",
  Washington: "Olympia",
  Wyoming: "Cheyenne",

  // ── Провинции и территории Канады ──────────────────────────────────
  Alberta: "Edmonton",
  "British Columbia": "Victoria",
  Manitoba: "Winnipeg",
  "New Brunswick": "Fredericton",
  "Newfoundland and Labrador": "St. John's",
  Newfoundland: "St. John's",
  "Nova Scotia": "Halifax",
  Ontario: "Toronto",
  "Prince Edward Island": "Charlottetown",
  "Prince-Edward": "Charlottetown",
  Quebec: "Quebec City",
  Saskatchewan: "Regina",
  "Northwest Territories": "Yellowknife",
  Nunavut: "Iqaluit",
  Yukon: "Whitehorse",

  // ── Штаты и территории Австралии ───────────────────────────────────
  "New South Wales": "Sydney",
  Victoria: "Melbourne",
  Queensland: "Brisbane",
  "South Australia": "Adelaide",
  "Western Australia": "Perth",
  Tasmania: "Hobart",
  "Northern Territory": "Darwin",

  // ── Штаты Индии ────────────────────────────────────────────────────
  "Andhra Pradesh": "Amaravati",
  "Arunachal Pradesh": "Itanagar",
  Assam: "Dispur",
  Bihar: "Patna",
  Chhattisgarh: "Raipur",
  Goa: "Panaji",
  Gujarat: "Gandhinagar",
  Haryana: "Chandigarh",
  "Himachal Pradesh": "Shimla",
  Jharkhand: "Ranchi",
  Karnataka: "Bengaluru",
  Kerala: "Thiruvananthapuram",
  "Madhya Pradesh": "Bhopal",
  Maharashtra: "Mumbai",
  Manipur: "Imphal",
  Meghalaya: "Shillong",
  Mizoram: "Aizawl",
  Nagaland: "Kohima",
  Odisha: "Bhubaneswar",
  Rajasthan: "Jaipur",
  Sikkim: "Gangtok",
  "Tamil Nadu": "Chennai",
  Telangana: "Hyderabad",
  Tripura: "Agartala",
  "Uttar Pradesh": "Lucknow",
  Uttarakhand: "Dehradun",
  "West Bengal": "Kolkata",
  Puducherry: "Puducherry",
  Lakshadweep: "Kavaratti",
  "Andaman & Nicobar Islands": "Port Blair",

  // ── Провинции Пакистана ────────────────────────────────────────────
  Sindh: "Karachi",
  Balochistan: "Quetta",
  "Khyber Pakhtunkhwa": "Peshawar",
  "Gilgit-Baltistan": "Gilgit",
  "Azad Kashmir": "Muzaffarabad",

  // ── Земли Германии ─────────────────────────────────────────────────
  Bavaria: "Munich",
  Hamburg: "Hamburg",
  "Schleswig-Holstein": "Kiel",
  "Mecklenburg-Schwerin": "Schwerin",
  Oldenburg: "Oldenburg",
  Hanover: "Hanover",

  // ── Регионы Италии ─────────────────────────────────────────────────
  Lombardy: "Milan",
  Veneto: "Venice",
  Tuscany: "Florence",
  Campania: "Naples",
  Sicily: "Palermo",
  Sicilia: "Palermo",
  Apulia: "Bari",
  Calabria: "Catanzaro",
  Basilicata: "Potenza",
  Abruzzo: "L'Aquila",
  Tyrol: "Innsbruck",

  // ── Регионы Испании / Греции ───────────────────────────────────────
  Andalusia: "Seville",
  Catalonia: "Barcelona",
  Baleares: "Palma",
  "Central Macedonia": "Thessaloniki",

  // ── Провинции Китая ────────────────────────────────────────────────
  Guangdong: "Guangzhou",
  Guangxi: "Nanning",
  Hainan: "Haikou",
  Fujian: "Fuzhou",
  Shandong: "Jinan",
  Hebei: "Shijiazhuang",
  Heilongjiang: "Harbin",
  Liaoning: "Shenyang",
  Jilin: "Changchun",
  Yunnan: "Kunming",
  Shanghai: "Shanghai",
  Tianjin: "Tianjin",

  // ── Провинции Индонезии / Малайзии ─────────────────────────────────
  Aceh: "Banda Aceh",
  Bali: "Denpasar",
  Papua: "Jayapura",
  "West Papua": "Manokwari",
  "North Sumatra": "Medan",
  "South Sumatra": "Palembang",
  "West Sumatra": "Padang",
  Riau: "Pekanbaru",
  Sabah: "Kota Kinabalu",
  Sarawak: "Kuching",

  // ── Штаты Бразилии / Мексики ───────────────────────────────────────
  Bahia: "Salvador",
  Amazonas: "Manaus",
  Pará: "Belém",
  Sonora: "Hermosillo",
  Sinaloa: "Culiacán",
  Yucatan: "Mérida",
  Chihuahua: "Chihuahua",
  "Baja California": "Mexicali",
  "Baja California Sur": "La Paz",
  "Quintana Roo": "Chetumal",

  // ── Прочие территории / автономии ──────────────────────────────────
  Greenland: "Nuuk",
  "Faroe Islands": "Tórshavn",
  Guam: "Hagåtña",
  "Puerto Rico": "San Juan",
  Bermuda: "Hamilton",
  Aruba: "Oranjestad",
  Curaçao: "Willemstad",
  "Cayman Islands": "George Town",
  "Falkland Islands": "Stanley",
  "New Caledonia": "Nouméa",
  "French Guiana": "Cayenne",
  Martinique: "Fort-de-France",
  Guadeloupe: "Basse-Terre",
  "Northern Mariana Islands": "Saipan",
  Svalbard: "Longyearbyen",
  Okinawa: "Naha",
  Jeju: "Jeju City",
};

// Пул имён для СТОЛИЦ ИГРОКОВ и наций-регионов (нет реальной страны). Выдуманные
// «державные» названия. Детерминированный выбор по хешу id владельца.
export const CAPITAL_POOL: string[] = [
  "Zarnitsa",
  "Krepost",
  "Volograd",
  "Svetlograd",
  "Ostrograd",
  "Vysengrad",
  "Zvezdny",
  "Granitny",
  "Orlinsk",
  "Belogorsk",
  "Kordon",
  "Ravengrad",
  "Zheleznov",
  "Solntsegrad",
  "Novomir",
  "Vernost",
  "Bastion",
  "Terragrad",
  "Yargrad",
  "Stalgorod",
  "Vysota",
  "Kamengrad",
  "Zolotoy",
  "Vityaz",
];

// RU-оверлей по EN-ключу (столица EN → RU). Нет ключа → показываем EN.
export const CAPITAL_RU: Record<string, string> = {
  Moscow: "Москва",
  Washington: "Вашингтон",
  Beijing: "Пекин",
  Berlin: "Берлин",
  Paris: "Париж",
  London: "Лондон",
  Rome: "Рим",
  Madrid: "Мадрид",
  Lisbon: "Лиссабон",
  Warsaw: "Варшава",
  Kyiv: "Киев",
  Minsk: "Минск",
  Ankara: "Анкара",
  Tokyo: "Токио",
  "New Delhi": "Нью-Дели",
  Brasília: "Бразилиа",
  Ottawa: "Оттава",
  "Mexico City": "Мехико",
  "Buenos Aires": "Буэнос-Айрес",
  Canberra: "Канберра",
  Cairo: "Каир",
  Tehran: "Тегеран",
  Baghdad: "Багдад",
  Riyadh: "Эр-Рияд",
  Astana: "Астана",
  Ulaanbaatar: "Улан-Батор",
  Stockholm: "Стокгольм",
  Oslo: "Осло",
  Helsinki: "Хельсинки",
  Copenhagen: "Копенгаген",
  Amsterdam: "Амстердам",
  Brussels: "Брюссель",
  Bern: "Берн",
  Vienna: "Вена",
  Athens: "Афины",
  Bucharest: "Бухарест",
  Sofia: "София",
  Budapest: "Будапешт",
  Prague: "Прага",
  Bratislava: "Братислава",
  Belgrade: "Белград",
  Zagreb: "Загреб",
  Dublin: "Дублин",
  Reykjavik: "Рейкьявик",
  Kabul: "Кабул",
  Islamabad: "Исламабад",
  Dhaka: "Дакка",
  Jakarta: "Джакарта",
  Bangkok: "Бангкок",
  Hanoi: "Ханой",
  Seoul: "Сеул",
  Pyongyang: "Пхеньян",
  Manila: "Манила",
  "Kuala Lumpur": "Куала-Лумпур",
  Naypyidaw: "Нейпьидо",
  Abuja: "Абуджа",
  "Addis Ababa": "Аддис-Абеба",
  Nairobi: "Найроби",
  Pretoria: "Претория",
  Algiers: "Алжир",
  Rabat: "Рабат",
  Luanda: "Луанда",
  Tripoli: "Триполи",
  Khartoum: "Хартум",
  Bogotá: "Богота",
  Caracas: "Каракас",
  Lima: "Лима",
  Santiago: "Сантьяго",
  Sucre: "Сукре",
  Yerevan: "Ереван",
  Tbilisi: "Тбилиси",
  Baku: "Баку",
  Tashkent: "Ташкент",
  Jerusalem: "Иерусалим",
  Damascus: "Дамаск",
  Amman: "Амман",
  Wellington: "Веллингтон",
  Havana: "Гавана",
  Tirana: "Тирана",
  Tallinn: "Таллин",
  Riga: "Рига",
  Vilnius: "Вильнюс",
  Ljubljana: "Любляна",
  Doha: "Доха",
  "Abu Dhabi": "Абу-Даби",
  Muscat: "Маскат",
  Sanaa: "Сана",
  // Столицы, добавленные при расширении
  Quito: "Кито",
  Asunción: "Асунсьон",
  Montevideo: "Монтевидео",
  Georgetown: "Джорджтаун",
  Paramaribo: "Парамарибо",
  Ashgabat: "Ашхабад",
  Dushanbe: "Душанбе",
  Beirut: "Бейрут",
  Manama: "Манама",
  "Kuwait City": "Эль-Кувейт",
  "Andorra la Vella": "Андорра-ла-Велья",
  Monaco: "Монако",
  Vaduz: "Вадуц",
  Valletta: "Валлетта",
  Nicosia: "Никосия",
  Pristina: "Приштина",
  Podgorica: "Подгорица",
  Skopje: "Скопье",
  Sarajevo: "Сараево",
  Chișinău: "Кишинёв",
  Kathmandu: "Катманду",
  Thimphu: "Тхимпху",
  Colombo: "Коломбо",
  Malé: "Мале",
  "Phnom Penh": "Пномпень",
  Vientiane: "Вьентьян",
  "Bandar Seri Begawan": "Бандар-Сери-Бегаван",
  Singapore: "Сингапур",
  Dili: "Дили",
  Taipei: "Тайбэй",
  Suva: "Сува",
  Apia: "Апиа",
  "Port Moresby": "Порт-Морсби",
  Honiara: "Хониара",
  Ngerulmud: "Нгерулмуд",
  Palikir: "Паликир",
  Accra: "Аккра",
  Dakar: "Дакар",
  Bamako: "Бамако",
  Niamey: "Ниамей",
  "N'Djamena": "Нджамена",
  Nouakchott: "Нуакшот",
  Libreville: "Либревиль",
  Bangui: "Банги",
  Kinshasa: "Киншаса",
  "Porto-Novo": "Порто-Ново",
  Monrovia: "Монровия",
  Freetown: "Фритаун",
  Asmara: "Асмэра",
  Mogadishu: "Могадишо",
  Dodoma: "Додома",
  Maputo: "Мапуту",
  Lusaka: "Лусака",
  Harare: "Хараре",
  Gaborone: "Габороне",
  Windhoek: "Виндхук",
  Antananarivo: "Антананариву",
  "Guatemala City": "Гватемала",
  Tegucigalpa: "Тегусигальпа",
  Managua: "Манагуа",
  "Panama City": "Панама",
  Belmopan: "Бельмопан",
  "Port-au-Prince": "Порт-о-Пренс",
  "Santo Domingo": "Санто-Доминго",
  Kingston: "Кингстон",
  Nassau: "Нассау",
  Bridgetown: "Бриджтаун",
  Roseau: "Розо",
  "St. George's": "Сент-Джорджес",
  "Port of Spain": "Порт-оф-Спейн",
  "Saint John's": "Сент-Джонс",
  Basseterre: "Бастер",
  Castries: "Кастри",
  Kingstown: "Кингстаун",
  Ramallah: "Рамалла",
  Djibouti: "Джибути",
  Juba: "Джуба",
  Tunis: "Тунис",
  // Исторические
  Persepolis: "Персеполь",
  Ctesiphon: "Ктесифон",
  Constantinople: "Константинополь",
  Alexandria: "Александрия",
  Carthage: "Карфаген",
  Mecca: "Мекка",
  Naples: "Неаполь",
  Turin: "Турин",
  Pamplona: "Памплона",
  León: "Леон",
  Palma: "Пальма",
  Valencia: "Валенсия",
  "Santiago de Compostela": "Сантьяго-де-Компостела",
  Oviedo: "Овьедо",
  Zaragoza: "Сарагоса",
  Granada: "Гранада",
  Fez: "Фес",
  Rouen: "Руан",
  Bordeaux: "Бордо",
  Dijon: "Дижон",
  Kyzyl: "Кызыл",
  Lhasa: "Лхаса",
  Winchester: "Винчестер",
  // Британские нации
  Edinburgh: "Эдинбург",
  Cardiff: "Кардифф",
  Belfast: "Белфаст",
  // Постсоветские
  "Alma-Ata": "Алма-Ата",
  Frunze: "Фрунзе",
  Tiraspol: "Тирасполь",
  Sukhumi: "Сухуми",
  Tskhinvali: "Цхинвали",
  "Banja Luka": "Баня-Лука",
  "Ulan-Ude": "Улан-Удэ",
  Grozny: "Грозный",
  Makhachkala: "Махачкала",
  Magas: "Магас",
  Maykop: "Майкоп",
  Elista: "Элиста",
  Nalchik: "Нальчик",
  Cherkessk: "Черкесск",
  Vladikavkaz: "Владикавказ",
  Syktyvkar: "Сыктывкар",
  Yakutsk: "Якутск",
  Astrakhan: "Астрахань",
  Irkutsk: "Иркутск",
  "Rostov-on-Don": "Ростов-на-Дону",
  Krasnodar: "Краснодар",
  Stavropol: "Ставрополь",
  Vladivostok: "Владивосток",
  Magadan: "Магадан",
  // Штаты США
  Montgomery: "Монтгомери",
  Juneau: "Джуно",
  Phoenix: "Финикс",
  "Little Rock": "Литл-Рок",
  Sacramento: "Сакраменто",
  Denver: "Денвер",
  Tallahassee: "Таллахасси",
  Honolulu: "Гонолулу",
  Boise: "Бойсе",
  Springfield: "Спрингфилд",
  Indianapolis: "Индианаполис",
  "Des Moines": "Де-Мойн",
  Topeka: "Топика",
  Frankfort: "Франкфорт",
  "Baton Rouge": "Батон-Руж",
  Augusta: "Огаста",
  Boston: "Бостон",
  Lansing: "Лансинг",
  "Saint Paul": "Сент-Пол",
  Jackson: "Джэксон",
  "Jefferson City": "Джефферсон-Сити",
  Helena: "Хелена",
  Lincoln: "Линкольн",
  "Carson City": "Карсон-Сити",
  "Santa Fe": "Санта-Фе",
  Albany: "Олбани",
  Raleigh: "Роли",
  Bismarck: "Бисмарк",
  Columbus: "Колумбус",
  "Oklahoma City": "Оклахома-Сити",
  Salem: "Сейлем",
  Harrisburg: "Гаррисберг",
  Columbia: "Колумбия",
  Pierre: "Пирр",
  Nashville: "Нашвилл",
  Austin: "Остин",
  "Salt Lake City": "Солт-Лейк-Сити",
  Montpelier: "Монтпилиер",
  Richmond: "Ричмонд",
  Olympia: "Олимпия",
  Cheyenne: "Шайенн",
  // Канада
  Edmonton: "Эдмонтон",
  Victoria: "Виктория",
  Winnipeg: "Виннипег",
  Fredericton: "Фредериктон",
  "St. John's": "Сент-Джонс",
  Halifax: "Галифакс",
  Toronto: "Торонто",
  Charlottetown: "Шарлоттаун",
  "Quebec City": "Квебек",
  Regina: "Реджайна",
  Yellowknife: "Йеллоунайф",
  Iqaluit: "Икалуит",
  Whitehorse: "Уайтхорс",
  // Австралия
  Sydney: "Сидней",
  Melbourne: "Мельбурн",
  Brisbane: "Брисбен",
  Adelaide: "Аделаида",
  Perth: "Перт",
  Hobart: "Хобарт",
  Darwin: "Дарвин",
  // Индия
  Amaravati: "Амаравати",
  Itanagar: "Итанагар",
  Dispur: "Диспур",
  Patna: "Патна",
  Raipur: "Райпур",
  Panaji: "Панаджи",
  Gandhinagar: "Гандинагар",
  Chandigarh: "Чандигарх",
  Shimla: "Шимла",
  Ranchi: "Ранчи",
  Bengaluru: "Бангалор",
  Thiruvananthapuram: "Тируванантапурам",
  Bhopal: "Бхопал",
  Mumbai: "Мумбаи",
  Imphal: "Импхал",
  Shillong: "Шиллонг",
  Aizawl: "Айзавл",
  Kohima: "Кохима",
  Bhubaneswar: "Бхубанешвар",
  Jaipur: "Джайпур",
  Gangtok: "Гангток",
  Chennai: "Ченнаи",
  Hyderabad: "Хайдарабад",
  Agartala: "Агартала",
  Lucknow: "Лакхнау",
  Dehradun: "Дехрадун",
  Kolkata: "Калькутта",
  Puducherry: "Пудучерри",
  Kavaratti: "Каваратти",
  "Port Blair": "Порт-Блэр",
  // Пакистан
  Karachi: "Карачи",
  Quetta: "Кветта",
  Peshawar: "Пешавар",
  Gilgit: "Гилгит",
  Muzaffarabad: "Музаффарабад",
  // Германия
  Munich: "Мюнхен",
  Hamburg: "Гамбург",
  Kiel: "Киль",
  Schwerin: "Шверин",
  Oldenburg: "Ольденбург",
  Hanover: "Ганновер",
  // Италия
  Milan: "Милан",
  Venice: "Венеция",
  Florence: "Флоренция",
  Palermo: "Палермо",
  Bari: "Бари",
  Catanzaro: "Катандзаро",
  Potenza: "Потенца",
  "L'Aquila": "Л'Акуила",
  Innsbruck: "Инсбрук",
  // Испания / Греция
  Seville: "Севилья",
  Barcelona: "Барселона",
  Thessaloniki: "Салоники",
  // Китай
  Guangzhou: "Гуанчжоу",
  Nanning: "Наньнин",
  Haikou: "Хайкоу",
  Fuzhou: "Фучжоу",
  Jinan: "Цзинань",
  Shijiazhuang: "Шицзячжуан",
  Harbin: "Харбин",
  Shenyang: "Шэньян",
  Changchun: "Чанчунь",
  Kunming: "Куньмин",
  Shanghai: "Шанхай",
  Tianjin: "Тяньцзинь",
  // Индонезия / Малайзия
  "Banda Aceh": "Банда-Ачех",
  Denpasar: "Денпасар",
  Jayapura: "Джаяпура",
  Manokwari: "Маноквари",
  Medan: "Медан",
  Palembang: "Палембанг",
  Padang: "Паданг",
  Pekanbaru: "Пеканбару",
  "Kota Kinabalu": "Кота-Кинабалу",
  Kuching: "Кучинг",
  // Бразилия / Мексика
  Salvador: "Салвадор",
  Manaus: "Манаус",
  Belém: "Белен",
  Hermosillo: "Эрмосильо",
  Culiacán: "Кульякан",
  Mérida: "Мерида",
  Chihuahua: "Чиуауа",
  Mexicali: "Мехикали",
  "La Paz": "Ла-Пас",
  Chetumal: "Четумаль",
  // Прочие территории
  Nuuk: "Нуук",
  Tórshavn: "Торсхавн",
  Hagåtña: "Хагатна",
  "San Juan": "Сан-Хуан",
  Hamilton: "Гамильтон",
  Oranjestad: "Ораньестад",
  Willemstad: "Виллемстад",
  "George Town": "Джорджтаун",
  Stanley: "Стэнли",
  Nouméa: "Нумеа",
  Cayenne: "Кайенна",
  "Fort-de-France": "Фор-де-Франс",
  "Basse-Terre": "Бас-Тер",
  Saipan: "Сайпан",
  Longyearbyen: "Лонгйир",
  Naha: "Наха",
  "Jeju City": "Чеджу",
  // Пул игроков
  Zarnitsa: "Зарница",
  Krepost: "Крепость",
  Volograd: "Волоград",
  Svetlograd: "Светлоград",
  Ostrograd: "Остроград",
  Vysengrad: "Высенград",
  Zvezdny: "Звёздный",
  Granitny: "Гранитный",
  Orlinsk: "Орлинск",
  Belogorsk: "Белогорск",
  Kordon: "Кордон",
  Ravengrad: "Равенград",
  Zheleznov: "Железнов",
  Solntsegrad: "Солнцеград",
  Novomir: "Новомир",
  Vernost: "Верность",
  Bastion: "Бастион",
  Terragrad: "Терраград",
  Yargrad: "Ярград",
  Stalgorod: "Сталгород",
  Vysota: "Высота",
  Kamengrad: "Каменград",
  Zolotoy: "Золотой",
  Vityaz: "Витязь",
};

/**
 * Детерминированное имя столицы (EN-канон). Нация с именем реальной страны →
 * реальная столица; иначе (игрок / нация-регион) → элемент пула по хешу id.
 * seedId — стабильный id владельца (одинаков на всех клиентах → детерминизм).
 */
export function pickCapitalName(
  ownerName: string,
  isNation: boolean,
  seedId: string,
): string {
  if (isNation) {
    const cap = NATION_CAPITAL[ownerName.trim()];
    if (cap) return cap;
  }
  const rand = new PseudoRandom(simpleHash(seedId));
  return rand.randElement(CAPITAL_POOL);
}

// terron 05.08: ПОКОЛЕНИЕ СТОЛИЦЫ. Имя столицы сеется id игрока, поэтому у
// одного игрока оно ВСЕГДА одно и то же: потерял столицу, построил новую — и на
// карте две «Зарницы» (текущая золотом, бывшая тускло). Отличие по цвету игрок
// не читает (репорт владельца), поэтому вторую и следующие подписываем словом
// «Новая». Префикс НЕ хранится в имени: канон остаётся EN-ключом для CAPITAL_RU,
// а склеивается на рендере — иначе RU-словарь перестал бы находить название.
//
// Род нужен для русского: «Новая Зарница», но «Новый Волоград», «Новое …».
// Список пула короткий (24 имени), поэтому род задан явно, а для столиц НАЦИЙ
// (Москва, Париж, Токио…) работает эвристика по окончанию — она на реальных
// топонимах ошибается редко, и цена ошибки — одна неверная буква в подписи.
const CAPITAL_GENDER_RU: Record<string, "m" | "f" | "n"> = {
  Zarnitsa: "f", // Зарница
  Krepost: "f", // Крепость
  Vernost: "f", // Верность
  Vysota: "f", // Высота
  Volograd: "m",
  Svetlograd: "m",
  Ostrograd: "m",
  Vysengrad: "m",
  Zvezdny: "m", // Звёздный
  Granitny: "m", // Гранитный
  Orlinsk: "m",
  Belogorsk: "m",
  Kordon: "m",
  Ravengrad: "m",
  Zheleznov: "m",
  Solntsegrad: "m",
  Novomir: "m",
  Bastion: "m",
  Terragrad: "m",
  Yargrad: "m",
  Stalgorod: "m",
  Kamengrad: "m",
  Zolotoy: "m", // Золотой
  Vityaz: "m", // Витязь
};

/** Род RU-названия: явный для пула, по окончанию — для столиц наций. */
function genderRu(canon: string, ruName: string): "m" | "f" | "n" {
  const known = CAPITAL_GENDER_RU[canon];
  if (known) return known;
  const last = ruName.slice(-1).toLowerCase();
  if (last === "а" || last === "я") return "f";
  if (last === "о" || last === "е") return "n";
  return "m";
}

/**
 * Подпись столицы с учётом поколения: 1 — как есть, 2 — «Новая X»,
 * дальше «Новая X II», «Новая X III» (римская цифра = поколение − 1), чтобы
 * третья столица не совпала со второй.
 */
export function capitalLabel(
  canon: string,
  ruName: string,
  ru: boolean,
  generation: number,
): string {
  const base = ru ? ruName : canon;
  if (generation <= 1) return base;
  const prefix = ru
    ? { m: "Новый", f: "Новая", n: "Новое" }[genderRu(canon, ruName)]
    : "New";
  const roman = ["", "", "", "II", "III", "IV", "V", "VI", "VII", "VIII"];
  const tail = generation >= 3 ? ` ${roman[generation] ?? generation - 1}` : "";
  return `${prefix} ${base}${tail}`;
}
